"use client";

import { useEffect, useState, Suspense, useCallback } from "react";
import { useSearchParams } from "next/navigation";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Textarea } from "@/components/ui/textarea";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from "@/components/ui/dialog";
import {
  api,
  Post,
  Pillar,
  AutoGeneratedPost,
  ValidationResult,
  VisualSuggestion,
} from "@/lib/api";

const Spinner = () => (
  <svg className="animate-spin h-4 w-4" viewBox="0 0 24 24">
    <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" fill="none" />
    <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4z" />
  </svg>
);

const statusConfig: Record<string, { label: string; className: string }> = {
  draft: { label: "Brouillon", className: "bg-gray-100 text-gray-700" },
  review: { label: "En revue", className: "bg-yellow-100 text-yellow-700" },
  approved: { label: "Approuvé", className: "bg-blue-100 text-blue-700" },
  scheduled: { label: "Planifié", className: "bg-purple-100 text-purple-700" },
  published: { label: "Publié", className: "bg-green-100 text-green-700" },
  failed: { label: "Échoué", className: "bg-red-100 text-red-700" },
};

function ValidationBadge({ score }: { score: number }) {
  const color =
    score >= 80
      ? "bg-green-100 text-green-700"
      : score >= 50
        ? "bg-yellow-100 text-yellow-700"
        : "bg-red-100 text-red-700";
  return <Badge className={color}>Anti-IA: {score}</Badge>;
}

// ─── Generate Dialog ─────────────────────────────────────────
function GenerateDialog({
  defaultTopic,
  defaultIdeaId,
  onOpenChange,
  externalOpen,
  onGenerated,
}: {
  defaultTopic?: string;
  defaultIdeaId?: string;
  onOpenChange?: (open: boolean) => void;
  externalOpen?: boolean;
  onGenerated?: () => void;
}) {
  const [topic, setTopic] = useState(defaultTopic || "");
  const [generating, setGenerating] = useState(false);
  const [result, setResult] = useState<AutoGeneratedPost | null>(null);
  const [editedContent, setEditedContent] = useState("");
  const [revalidation, setRevalidation] = useState<ValidationResult | null>(null);
  const [open, setOpen] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const isOpen = externalOpen !== undefined ? externalOpen : open;
  const handleOpenChange = (v: boolean) => {
    setOpen(v);
    onOpenChange?.(v);
    if (!v && result) onGenerated?.();
  };

  useEffect(() => {
    if (isOpen && defaultTopic) {
      setTopic(defaultTopic);
      setResult(null);
      setError(null);
      setRevalidation(null);
    }
  }, [isOpen, defaultTopic]);

  const handleGenerate = async () => {
    if (!topic.trim()) return;
    setGenerating(true);
    setResult(null);
    setRevalidation(null);
    setError(null);
    try {
      const generated = await api.generateAutoPost({
        topic: topic.trim(),
        idea_id: defaultIdeaId,
        save_as_draft: true,
      });
      setResult(generated);
      setEditedContent(generated.content);
    } catch (err) {
      setError(err instanceof Error ? err.message : "Erreur de génération");
    } finally {
      setGenerating(false);
    }
  };

  const handleRevalidate = async () => {
    if (!editedContent) return;
    const validation = await api.validatePost(editedContent);
    setRevalidation(validation);
  };

  const handleSaveEdit = async () => {
    if (!result?.post_id || !editedContent) return;
    await api.updatePost(result.post_id, { content: editedContent });
    if (revalidation) await handleRevalidate();
  };

  const dialogContent = (
    <DialogContent className="max-w-[680px] w-full max-h-[95vh] overflow-y-auto">
      <DialogHeader>
        <DialogTitle>Générer un post LinkedIn</DialogTitle>
      </DialogHeader>
      <div className="space-y-4 pt-2">
        <div>
          <label className="text-sm font-medium text-gray-700 mb-1 block">
            De quoi voulez-vous parler ?
          </label>
          <Textarea
            placeholder="Ex: Parler du fait que 80% des LP n'ont pas de message match, raconter comment un client a doublé son CR..."
            value={topic}
            onChange={(e) => setTopic(e.target.value)}
            className="min-h-[100px]"
            onKeyDown={(e) => { if (e.key === "Enter" && e.metaKey) handleGenerate(); }}
          />
          <p className="text-xs text-gray-400 mt-1">
            L&apos;IA choisit automatiquement le meilleur pilier et template. Cmd+Enter pour lancer.
          </p>
        </div>
        <Button onClick={handleGenerate} disabled={!topic.trim() || generating} className="w-full">
          {generating ? (
            <span className="flex items-center gap-2">
              <svg className="animate-spin h-4 w-4" viewBox="0 0 24 24">
                <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" fill="none" />
                <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4z" />
              </svg>
              L&apos;IA analyse et génère...
            </span>
          ) : "Générer le post"}
        </Button>
        {error && <div className="bg-red-50 text-red-700 rounded px-4 py-3 text-sm">{error}</div>}
        {result && (
          <div className="space-y-4 border-t pt-4">
            <div className="bg-blue-50 rounded-lg px-4 py-3 space-y-1">
              <div className="flex items-center gap-2 flex-wrap">
                <Badge className="bg-blue-100 text-blue-700">{result.pillar_name}</Badge>
                <Badge className="bg-indigo-100 text-indigo-700">{result.template_name}</Badge>
                <ValidationBadge score={(revalidation || result.validation).score} />
                {result.post_id && <Badge variant="outline">Sauvé en brouillon</Badge>}
              </div>
              <p className="text-xs text-blue-600 mt-1">{result.reasoning}</p>
            </div>
            <Textarea
              value={editedContent}
              onChange={(e) => setEditedContent(e.target.value)}
              className="min-h-[400px] text-[14px] leading-[1.42] text-gray-900 border-gray-200"
              style={{ fontFamily: '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif' }}
            />
            <div className="flex gap-2 flex-wrap">
              <Button variant="outline" onClick={handleRevalidate} size="sm">Re-valider anti-IA</Button>
              <Button variant="outline" onClick={handleSaveEdit} size="sm" disabled={editedContent === result.content}>
                Sauvegarder
              </Button>
              <Button onClick={handleGenerate} variant="outline" size="sm" disabled={generating}>Regénérer</Button>
            </div>
            {(revalidation || result.validation).issues.length > 0 && (
              <div className="space-y-2">
                <h4 className="text-sm font-medium text-gray-700">Validation anti-IA</h4>
                {(revalidation || result.validation).issues.map((issue, i) => (
                  <div key={i} className={`text-sm rounded px-3 py-2 ${issue.severity === "error" ? "bg-red-50 text-red-700" : "bg-yellow-50 text-yellow-700"}`}>
                    <span className="font-medium">{issue.rule}</span>
                    <span className="block text-xs mt-0.5">{issue.detail}</span>
                  </div>
                ))}
              </div>
            )}
          </div>
        )}
      </div>
    </DialogContent>
  );

  if (externalOpen !== undefined) {
    return <Dialog open={isOpen} onOpenChange={handleOpenChange}>{dialogContent}</Dialog>;
  }
  return (
    <Dialog open={isOpen} onOpenChange={handleOpenChange}>
      <DialogTrigger className="inline-flex items-center justify-center gap-2 whitespace-nowrap rounded-md text-sm font-medium bg-primary text-primary-foreground shadow-xs hover:bg-primary/90 h-9 px-4 py-2">
        Générer avec IA
      </DialogTrigger>
      {dialogContent}
    </Dialog>
  );
}

// ─── Visual Suggestion Panel ─────────────────────────────────
function VisualSuggestionPanel({ post, pillarName }: { post: Post; pillarName: string }) {
  const [suggestion, setSuggestion] = useState<VisualSuggestion | null>(null);
  const [loading, setLoading] = useState(false);
  const [loaded, setLoaded] = useState(false);

  const loadSuggestion = async () => {
    setLoading(true);
    try {
      const result = await api.suggestVisual(post.content, pillarName);
      setSuggestion(result);
      setLoaded(true);
    } catch {
      setSuggestion(null);
    } finally {
      setLoading(false);
    }
  };

  if (!loaded) {
    return (
      <button
        onClick={loadSuggestion}
        disabled={loading}
        className="text-xs text-blue-600 hover:text-blue-800 flex items-center gap-1 mt-2"
      >
        {loading ? (
          <><svg className="animate-spin h-3 w-3" viewBox="0 0 24 24"><circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" fill="none" /><path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4z" /></svg> Analyse du visuel...</>
        ) : (
          <><span>🎨</span> Suggérer un visuel</>
        )}
      </button>
    );
  }

  if (!suggestion) return null;

  const typeIcons: Record<string, string> = {
    carousel: "📑 Carrousel PDF",
    image: "🖼️ Image statique",
    text_only: "📝 Texte seul",
  };

  return (
    <div className="mt-3 bg-gradient-to-r from-purple-50 to-blue-50 rounded-lg p-3 border border-purple-100">
      <div className="flex items-center gap-2 mb-1">
        <Badge className="bg-purple-100 text-purple-700 text-xs">
          {typeIcons[suggestion.visual_type] || suggestion.visual_type}
        </Badge>
        <span className="text-xs text-gray-500">{suggestion.reasoning}</span>
      </div>
      <p className="text-sm text-gray-700 mt-1">{suggestion.visual_description}</p>
      {suggestion.carousel_slides && suggestion.carousel_slides.length > 0 && (
        <div className="mt-2 space-y-1">
          <p className="text-xs font-medium text-purple-700">Plan du carrousel :</p>
          <div className="flex gap-2 overflow-x-auto pb-1">
            {suggestion.carousel_slides.map((slide) => (
              <div key={slide.slide_number} className="flex-shrink-0 w-36 bg-white rounded p-2 border border-purple-100 shadow-sm">
                <p className="text-xs font-medium text-gray-800 truncate">#{slide.slide_number} {slide.title}</p>
                <p className="text-xs text-gray-500 line-clamp-2 mt-0.5">{slide.content}</p>
              </div>
            ))}
          </div>
        </div>
      )}
    </div>
  );
}

// ─── Post Editor (full finalization) ─────────────────────────
function PostEditor({
  post,
  pillarName,
  onSaved,
  onClose,
}: {
  post: Post;
  pillarName: string;
  onSaved: () => void;
  onClose: () => void;
}) {
  const [content, setContent] = useState(post.content);
  const [format, setFormat] = useState(post.format || "text");
  const [saving, setSaving] = useState(false);
  const [publishing, setPublishing] = useState(false);
  const [publishResult, setPublishResult] = useState<string | null>(null);
  const [validation, setValidation] = useState<ValidationResult | null>(null);
  const [scheduledDate, setScheduledDate] = useState(
    post.scheduled_at ? new Date(post.scheduled_at).toISOString().slice(0, 16) : ""
  );
  const [showScheduler, setShowScheduler] = useState(false);
  const [currentStatus, setCurrentStatus] = useState(post.status);
  const [visualSuggestion, setVisualSuggestion] = useState<VisualSuggestion | null>(null);
  const [suggestingVisual, setSuggestingVisual] = useState(false);
  const [generatingImage, setGeneratingImage] = useState(false);
  const [imageUrl, setImageUrl] = useState(post.image_url || "");
  const [chatMessages, setChatMessages] = useState<{ role: string; content: string }[]>([]);
  const [chatInput, setChatInput] = useState("");
  const [chatLoading, setChatLoading] = useState(false);

  const handleSave = async () => {
    setSaving(true);
    try {
      await api.updatePost(post.id, { content, format } as Partial<Post>);
      onSaved();
    } catch (err) {
      console.error(err);
    } finally {
      setSaving(false);
    }
  };

  const handleValidate = async () => {
    const result = await api.validatePost(content);
    setValidation(result);
  };

  const handleApprove = async () => {
    await api.updatePost(post.id, { content, status: "approved", format } as Partial<Post>);
    setCurrentStatus("approved");
    onSaved();
  };

  const handleSchedule = async () => {
    if (!scheduledDate) return;
    await api.updatePost(post.id, {
      content,
      format,
      status: "scheduled",
      scheduled_at: new Date(scheduledDate).toISOString(),
    } as Partial<Post>);
    setCurrentStatus("scheduled");
    setShowScheduler(false);
    onSaved();
  };

  const handlePublish = async () => {
    if (!confirm("Publier ce post sur LinkedIn maintenant ?")) return;
    setPublishing(true);
    setPublishResult(null);
    try {
      // Save content first if changed
      if (content !== post.content || format !== post.format) {
        await api.updatePost(post.id, { content, format } as Partial<Post>);
      }
      const result = await api.publishPost(post.id);
      setPublishResult("Publié sur LinkedIn !");
      setCurrentStatus("published");
      onSaved();
    } catch (err) {
      setPublishResult(`Erreur: ${err instanceof Error ? err.message : "Échec de la publication"}`);
    } finally {
      setPublishing(false);
    }
  };

  const handleDelete = async () => {
    if (!confirm("Supprimer ce post ?")) return;
    await api.deletePost(post.id);
    onSaved();
    onClose();
  };

  const wordCount = content.split(/\s+/).filter(Boolean).length;
  const formatOptions = [
    { value: "text", label: "Texte seul", icon: "📝" },
    { value: "image_text", label: "Image + texte", icon: "🖼" },
    { value: "carousel", label: "Carousel", icon: "📑" },
  ];

  return (
    <Dialog open onOpenChange={(open) => { if (!open) onClose(); }}>
      <DialogContent className="!max-w-[1100px] w-[95vw] max-h-[95vh] overflow-y-auto p-0">
        {/* Header */}
        <div className="sticky top-0 bg-white z-10 border-b px-6 py-3 flex items-center justify-between">
          <div className="flex items-center gap-2 flex-wrap">
            <Badge className={statusConfig[currentStatus]?.className}>{statusConfig[currentStatus]?.label}</Badge>
            {pillarName && <Badge className="bg-blue-100 text-blue-700">{pillarName}</Badge>}
            {post.anti_ai_score !== null && <ValidationBadge score={post.anti_ai_score} />}
            <span className="text-xs text-gray-400">{wordCount} mots</span>
          </div>
          <div className="flex items-center gap-1.5">
            {formatOptions.map((f) => (
              <button
                key={f.value}
                onClick={() => setFormat(f.value)}
                className={`px-2.5 py-1 rounded-full text-xs font-medium transition-colors ${
                  format === f.value ? "bg-blue-600 text-white" : "bg-gray-100 text-gray-600 hover:bg-gray-200"
                }`}
              >
                {f.icon} {f.label}
              </button>
            ))}
          </div>
        </div>

        <div className="flex flex-col lg:flex-row">
          {/* Left: Content editor */}
          <div className="flex-1 px-6 py-4 border-r min-w-0">
            {/* Author header */}
            <div className="flex items-center gap-3 mb-4">
              <div className="w-10 h-10 bg-blue-600 rounded-full flex items-center justify-center text-white font-bold text-sm shrink-0">
                ST
              </div>
              <div>
                <p className="font-semibold text-gray-900 text-sm leading-tight">Sébastien Tortu</p>
                <p className="text-[11px] text-gray-500 leading-tight">Fondateur Boost Conversion | Expert CRO</p>
              </div>
            </div>

            {/* Content */}
            <Textarea
              value={content}
              onChange={(e) => setContent(e.target.value)}
              className="w-full min-h-[350px] border-0 shadow-none focus-visible:ring-0 text-[14px] leading-[1.42] text-gray-900 resize-none p-0"
              style={{ fontFamily: '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif' }}
            />

            {/* Engagement bar */}
            <div className="border-t mt-4 pt-3 flex items-center gap-6 text-gray-400 text-xs">
              <span>👍 J&apos;aime</span>
              <span>💬 Commenter</span>
              <span>🔄 Republier</span>
              <span>📤 Envoyer</span>
            </div>
          </div>

          {/* Right: Visual + Scheduling panel */}
          <div className="w-full lg:w-[360px] shrink-0 p-5 space-y-5 bg-gray-50">
            {/* Visual section */}
            <div className="space-y-3">
              <h3 className="text-xs font-semibold text-gray-500 uppercase tracking-wide">Visuel</h3>

              {/* Suggestion IA */}
              {!visualSuggestion && (
                <Button
                  variant="outline"
                  size="sm"
                  className="w-full text-xs"
                  disabled={suggestingVisual}
                  onClick={async () => {
                    setSuggestingVisual(true);
                    try {
                      const suggestion = await api.suggestVisual(content, pillarName);
                      setVisualSuggestion(suggestion);
                      if (suggestion.visual_type === "carousel") setFormat("carousel");
                      else if (suggestion.visual_type === "image") setFormat("image_text");
                      else setFormat("text");
                    } catch { /* ignore */ } finally { setSuggestingVisual(false); }
                  }}
                >
                  {suggestingVisual ? <><Spinner /> Analyse du visuel...</> : "Suggérer un visuel (IA)"}
                </Button>
              )}

              {visualSuggestion && (
                <div className="bg-gradient-to-r from-purple-50 to-blue-50 rounded-lg p-3 border border-purple-100 space-y-1.5">
                  <div className="flex items-center gap-2">
                    <Badge className="bg-purple-100 text-purple-700 text-xs">
                      {visualSuggestion.visual_type === "carousel" ? "Carousel" : visualSuggestion.visual_type === "image" ? "Image" : "Texte seul"}
                    </Badge>
                    <button onClick={() => setVisualSuggestion(null)} className="text-xs text-gray-400 ml-auto">Refaire</button>
                  </div>
                  <p className="text-xs text-gray-700">{visualSuggestion.visual_description}</p>
                  {visualSuggestion.carousel_slides && visualSuggestion.carousel_slides.length > 0 && (
                    <div className="space-y-1 mt-2">
                      <p className="text-[10px] font-medium text-purple-700">Plan du carousel :</p>
                      {visualSuggestion.carousel_slides.map((slide) => (
                        <p key={slide.slide_number} className="text-[10px] text-gray-600">#{slide.slide_number} {slide.title}</p>
                      ))}
                    </div>
                  )}
                </div>
              )}

              {/* Image preview / generation */}
              {format === "image_text" && (
                <div className="space-y-2">
                  {imageUrl ? (
                    <div className="relative">
                      <img src={imageUrl} alt="Post visual" className="w-full rounded-lg border" />
                      <button
                        onClick={() => { setImageUrl(""); api.updatePost(post.id, { image_url: "" } as Partial<Post>); }}
                        className="absolute top-1 right-1 bg-red-500 text-white rounded-full w-5 h-5 text-xs flex items-center justify-center"
                      >x</button>
                    </div>
                  ) : (
                    <div className="bg-white rounded-lg p-3 border border-dashed border-gray-300 text-center space-y-2">
                      <p className="text-sm text-gray-500">Aucune image</p>
                      <Button
                        size="sm"
                        className="w-full text-xs bg-indigo-600 hover:bg-indigo-700"
                        disabled={generatingImage}
                        onClick={async () => {
                          setGeneratingImage(true);
                          try {
                            const result = await api.generateImage({ post_content: content, pillar_name: pillarName });
                            setImageUrl(result.image_url);
                            await api.updatePost(post.id, { image_url: result.image_url } as Partial<Post>);
                          } catch (err) {
                            alert("Erreur de génération image: " + (err instanceof Error ? err.message : "Erreur"));
                          } finally { setGeneratingImage(false); }
                        }}
                      >
                        {generatingImage ? <><Spinner /> Génération DALL-E...</> : "Générer une image (DALL-E)"}
                      </Button>
                    </div>
                  )}
                </div>
              )}

              {/* Carousel */}
              {format === "carousel" && (
                <div className="bg-white rounded-lg p-3 border border-dashed border-gray-300 text-center space-y-2">
                  {post.carousel_url ? (
                    <>
                      <p className="text-sm text-green-700">Carousel PDF prêt</p>
                      <a href={post.carousel_url} target="_blank" rel="noopener noreferrer" className="text-xs text-blue-500 hover:underline">Voir le PDF</a>
                    </>
                  ) : (
                    <p className="text-xs text-gray-400">Carousel — utilisez la page Carousel pour générer les slides</p>
                  )}
                </div>
              )}

              {format === "text" && !visualSuggestion && (
                <div className="bg-white rounded-lg p-3 border text-center">
                  <p className="text-xs text-gray-400">Post texte uniquement</p>
                </div>
              )}
            </div>

            {/* Scheduling */}
            <div>
              <h3 className="text-xs font-semibold text-gray-500 uppercase tracking-wide mb-2">Programmation</h3>
              {currentStatus === "scheduled" && post.scheduled_at ? (
                <div className="bg-purple-50 rounded-lg p-3 border border-purple-200">
                  <p className="text-sm text-purple-700 font-medium">Programmé pour :</p>
                  <p className="text-sm text-purple-900">
                    {new Date(post.scheduled_at).toLocaleDateString("fr-FR", { weekday: "long", day: "numeric", month: "long" })}
                    {" à "}
                    {new Date(post.scheduled_at).toLocaleTimeString("fr-FR", { hour: "2-digit", minute: "2-digit" })}
                  </p>
                </div>
              ) : currentStatus === "published" ? (
                <div className="bg-green-50 rounded-lg p-3 border border-green-200">
                  <p className="text-sm text-green-700 font-medium">Publié</p>
                  {post.published_at && (
                    <p className="text-xs text-green-600">
                      {new Date(post.published_at).toLocaleDateString("fr-FR", { day: "numeric", month: "long", hour: "2-digit", minute: "2-digit" })}
                    </p>
                  )}
                </div>
              ) : showScheduler ? (
                <div className="bg-white rounded-lg p-3 border space-y-2">
                  <input
                    type="datetime-local"
                    value={scheduledDate}
                    onChange={(e) => setScheduledDate(e.target.value)}
                    className="w-full text-sm border rounded px-2 py-1.5"
                    min={new Date().toISOString().slice(0, 16)}
                  />
                  <div className="flex gap-2">
                    <Button size="sm" onClick={handleSchedule} disabled={!scheduledDate} className="flex-1 text-xs">
                      Programmer
                    </Button>
                    <Button size="sm" variant="outline" onClick={() => setShowScheduler(false)} className="text-xs">
                      Annuler
                    </Button>
                  </div>
                </div>
              ) : (
                <Button
                  variant="outline"
                  size="sm"
                  onClick={() => setShowScheduler(true)}
                  className="w-full text-xs"
                >
                  Programmer une date
                </Button>
              )}
            </div>

            {/* Validation */}
            {validation && (
              <div>
                <h3 className="text-xs font-semibold text-gray-500 uppercase tracking-wide mb-2">Validation anti-IA</h3>
                <div className="space-y-1.5">
                  <ValidationBadge score={validation.score} />
                  {validation.issues.length === 0 ? (
                    <p className="text-xs text-green-600">Le post semble naturel.</p>
                  ) : (
                    validation.issues.map((issue, i) => (
                      <div key={i} className={`text-xs rounded px-2 py-1.5 ${issue.severity === "error" ? "bg-red-50 text-red-700" : "bg-yellow-50 text-yellow-700"}`}>
                        <span className="font-medium">{issue.rule}</span>
                        <span className="block mt-0.5">{issue.detail}</span>
                      </div>
                    ))
                  )}
                </div>
              </div>
            )}

            {/* Publish result */}
            {publishResult && (
              <div className={`rounded-lg p-3 text-sm ${publishResult.startsWith("Erreur") ? "bg-red-50 text-red-700" : "bg-green-50 text-green-700"}`}>
                {publishResult}
              </div>
            )}

            {/* Chat with AI */}
            <div className="space-y-2">
              <h3 className="text-xs font-semibold text-gray-500 uppercase tracking-wide">Discuter avec l&apos;IA</h3>

              {/* Chat messages */}
              <div className="bg-white rounded-lg border max-h-[250px] overflow-y-auto">
                {chatMessages.length === 0 ? (
                  <div className="p-3 text-center">
                    <p className="text-xs text-gray-400">Posez une question sur ce post : angle, CTA, ton, structure...</p>
                  </div>
                ) : (
                  <div className="p-2 space-y-2">
                    {chatMessages.map((msg, i) => (
                      <div key={i} className={`text-xs rounded-lg px-3 py-2 ${msg.role === "user" ? "bg-blue-50 text-blue-900 ml-4" : "bg-gray-50 text-gray-800 mr-4"}`}>
                        <p className="font-medium text-[10px] text-gray-500 mb-0.5">{msg.role === "user" ? "Vous" : "IA"}</p>
                        <p className="whitespace-pre-wrap">{msg.content}</p>
                      </div>
                    ))}
                    {chatLoading && (
                      <div className="flex items-center gap-2 text-xs text-gray-400 px-3 py-2">
                        <Spinner /> Réflexion...
                      </div>
                    )}
                  </div>
                )}
              </div>

              {/* Chat input */}
              <div className="space-y-1.5">
                <Textarea
                  value={chatInput}
                  onChange={(e) => setChatInput(e.target.value)}
                  onKeyDown={async (e) => {
                    if (e.key === "Enter" && e.metaKey && chatInput.trim() && !chatLoading) {
                      e.preventDefault();
                      const userMsg = { role: "user", content: chatInput.trim() };
                      const newMessages = [...chatMessages, userMsg];
                      setChatMessages(newMessages);
                      setChatInput("");
                      setChatLoading(true);
                      try {
                        const result = await api.postChat({
                          post_content: content,
                          messages: newMessages,
                          pillar_name: pillarName,
                        });
                        setChatMessages([...newMessages, { role: "assistant", content: result.reply }]);
                        if (result.updated_post) {
                          setContent(result.updated_post);
                        }
                      } catch { /* ignore */ } finally { setChatLoading(false); }
                    }
                  }}
                  placeholder="Ex: Peux-tu retravailler le CTA ? Cmd+Enter pour envoyer"
                  className="min-h-[80px] text-sm"
                  disabled={chatLoading}
                />
                <Button
                  size="sm"
                  className="w-full text-xs"
                  disabled={!chatInput.trim() || chatLoading}
                  onClick={async () => {
                    if (!chatInput.trim()) return;
                    const userMsg = { role: "user", content: chatInput.trim() };
                    const newMessages = [...chatMessages, userMsg];
                    setChatMessages(newMessages);
                    setChatInput("");
                    setChatLoading(true);
                    try {
                      const result = await api.postChat({
                        post_content: content,
                        messages: newMessages,
                        pillar_name: pillarName,
                      });
                      setChatMessages([...newMessages, { role: "assistant", content: result.reply }]);
                      if (result.updated_post) {
                        setContent(result.updated_post);
                      }
                    } catch { /* ignore */ } finally { setChatLoading(false); }
                  }}
                >
                  {chatLoading ? <><Spinner /> Réflexion...</> : "Envoyer (Cmd+Enter)"}
                </Button>
              </div>
            </div>
          </div>
        </div>

        {/* Bottom action bar */}
        <div className="border-t px-6 py-3 flex gap-2 flex-wrap bg-white sticky bottom-0">
          <Button onClick={handleSave} disabled={saving || (content === post.content && format === post.format)} size="sm">
            {saving ? "Sauvegarde..." : "Sauvegarder"}
          </Button>
          <Button variant="outline" onClick={handleValidate} size="sm">
            Valider anti-IA
          </Button>
          {(currentStatus === "draft" || currentStatus === "review") && (
            <Button variant="outline" onClick={handleApprove} size="sm" className="text-green-700 border-green-300 hover:bg-green-50">
              Approuver
            </Button>
          )}
          {currentStatus !== "published" && (
            <Button
              onClick={handlePublish}
              disabled={publishing}
              size="sm"
              className="bg-blue-600 hover:bg-blue-700 text-white"
            >
              {publishing ? (
                <span className="flex items-center gap-1.5">
                  <svg className="animate-spin h-3.5 w-3.5" viewBox="0 0 24 24"><circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" fill="none" /><path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4z" /></svg>
                  Publication...
                </span>
              ) : "Publier sur LinkedIn"}
            </Button>
          )}
          <Button variant="outline" onClick={handleDelete} size="sm" className="text-red-500 border-red-200 hover:bg-red-50 ml-auto">
            Supprimer
          </Button>
        </div>
      </DialogContent>
    </Dialog>
  );
}

// ─── Post Card ───────────────────────────────────────────────
function PostCard({
  post,
  pillarName,
  onEdit,
  onRefresh,
}: {
  post: Post;
  pillarName: string;
  onEdit: () => void;
  onRefresh: () => void;
}) {
  const status = statusConfig[post.status] || statusConfig.draft;

  const handleApprove = async () => {
    await api.updatePost(post.id, { status: "approved" });
    onRefresh();
  };

  return (
    <Card className="hover:shadow-md transition-shadow h-full flex flex-col">
      <CardContent className="p-4 flex flex-col flex-1">
        <div className="flex items-center gap-1.5 mb-2 flex-wrap">
          <Badge className={`${status.className} text-[10px] px-1.5 py-0`}>{status.label}</Badge>
          {pillarName && (
            <Badge className="bg-blue-50 text-blue-600 text-[10px] px-1.5 py-0">{pillarName}</Badge>
          )}
          {post.anti_ai_score !== null && <ValidationBadge score={post.anti_ai_score} />}
        </div>

        {/* Hook highlight */}
        {post.hook && (
          <p className="text-sm font-semibold text-gray-900 mb-1 line-clamp-2">{post.hook}</p>
        )}

        {/* Body preview */}
        <p className="text-xs text-gray-600 line-clamp-4 whitespace-pre-wrap flex-1">
          {post.hook ? post.content.replace(post.hook, "").trim().substring(0, 200) : post.content.substring(0, 200)}
        </p>

        <div className="mt-3 pt-2 border-t flex items-center justify-between">
          <span className="text-[10px] text-gray-400">
            {new Date(post.created_at).toLocaleDateString("fr-FR", { day: "numeric", month: "short" })}
            {post.word_count ? ` · ${post.word_count} mots` : ""}
          </span>
          <div className="flex gap-1.5">
            {post.status === "draft" && (
              <Button size="sm" variant="ghost" onClick={handleApprove}
                className="text-green-700 hover:bg-green-50 h-7 text-xs px-2">
                ✓
              </Button>
            )}
            <Button variant="outline" size="sm" onClick={onEdit} className="h-7 text-xs px-2">
              Éditer
            </Button>
          </div>
        </div>

        {/* Visual suggestion */}
        <VisualSuggestionPanel post={post} pillarName={pillarName} />
      </CardContent>
    </Card>
  );
}

// ─── Main Posts Content ──────────────────────────────────────
function PostsContent() {
  const [posts, setPosts] = useState<Post[]>([]);
  const [pillars, setPillars] = useState<Pillar[]>([]);
  const [loading, setLoading] = useState(true);
  const [tab, setTab] = useState("all");
  const [pillarFilter, setPillarFilter] = useState<string>("all");
  const [editingPost, setEditingPost] = useState<Post | null>(null);
  const searchParams = useSearchParams();

  const ideaTopic = searchParams.get("topic");
  const ideaId = searchParams.get("idea_id");
  const [autoGenerateOpen, setAutoGenerateOpen] = useState(!!ideaTopic);

  const pillarMap = Object.fromEntries(pillars.map((p) => [p.id, p.name]));

  const loadPosts = useCallback(() => {
    const params: Record<string, string> = {};
    if (tab !== "all") params.status = tab;
    if (pillarFilter !== "all") params.pillar_id = pillarFilter;
    setLoading(true);
    api.listPosts(Object.keys(params).length ? params : undefined)
      .then(setPosts)
      .catch(console.error)
      .finally(() => setLoading(false));
  }, [tab, pillarFilter]);

  useEffect(() => { api.listPillars().then(setPillars).catch(console.error); }, []);
  useEffect(() => { loadPosts(); }, [loadPosts]);

  const filteredPosts = pillarFilter === "all"
    ? posts
    : posts.filter((p) => p.pillar_id === pillarFilter);

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <h1 className="text-2xl font-bold text-gray-900">Posts</h1>
        <GenerateDialog onGenerated={loadPosts} />
      </div>

      {ideaTopic && (
        <GenerateDialog
          defaultTopic={ideaTopic}
          defaultIdeaId={ideaId || undefined}
          externalOpen={autoGenerateOpen}
          onOpenChange={setAutoGenerateOpen}
          onGenerated={loadPosts}
        />
      )}

      {/* Filters bar */}
      <div className="flex gap-4 items-center flex-wrap">
        <Tabs value={tab} onValueChange={setTab}>
          <TabsList>
            <TabsTrigger value="all">Tous</TabsTrigger>
            <TabsTrigger value="draft">Brouillons</TabsTrigger>
            <TabsTrigger value="approved">Approuvés</TabsTrigger>
            <TabsTrigger value="scheduled">Planifiés</TabsTrigger>
            <TabsTrigger value="published">Publiés</TabsTrigger>
          </TabsList>
        </Tabs>

        {/* Pillar filter */}
        <div className="flex gap-1.5 flex-wrap">
          <button
            onClick={() => setPillarFilter("all")}
            className={`px-2.5 py-1 rounded-full text-xs font-medium transition-colors ${
              pillarFilter === "all" ? "bg-gray-900 text-white" : "bg-gray-100 text-gray-600 hover:bg-gray-200"
            }`}
          >
            Tous les piliers
          </button>
          {pillars.map((p) => (
            <button
              key={p.id}
              onClick={() => setPillarFilter(p.id)}
              className={`px-2.5 py-1 rounded-full text-xs font-medium transition-colors ${
                pillarFilter === p.id ? "bg-blue-600 text-white" : "bg-blue-50 text-blue-700 hover:bg-blue-100"
              }`}
            >
              {p.name}
            </button>
          ))}
        </div>
      </div>

      {/* Posts grid — 3 columns */}
      {loading ? (
        <p className="text-sm text-gray-500 text-center py-8">Chargement...</p>
      ) : filteredPosts.length === 0 ? (
        <Card>
          <CardContent className="p-6">
            <p className="text-sm text-gray-500 text-center py-8">
              Aucun post. Cliquez sur &quot;Générer avec IA&quot; pour créer votre premier post.
            </p>
          </CardContent>
        </Card>
      ) : (
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
          {filteredPosts.map((post) => (
            <PostCard
              key={post.id}
              post={post}
              pillarName={pillarMap[post.pillar_id || ""] || ""}
              onEdit={() => setEditingPost(post)}
              onRefresh={loadPosts}
            />
          ))}
        </div>
      )}

      {/* Editor dialog */}
      {editingPost && (
        <PostEditor
          post={editingPost}
          pillarName={pillarMap[editingPost.pillar_id || ""] || ""}
          onSaved={() => { setEditingPost(null); loadPosts(); }}
          onClose={() => setEditingPost(null)}
        />
      )}
    </div>
  );
}

export default function PostsPage() {
  return (
    <Suspense fallback={<p className="text-sm text-gray-500 text-center py-8">Chargement...</p>}>
      <PostsContent />
    </Suspense>
  );
}
