"use client";

import { useEffect, useState, Suspense, useCallback } from "react";
import { useSearchParams } from "next/navigation";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Textarea } from "@/components/ui/textarea";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from "@/components/ui/dialog";
import {
  api,
  Post,
  Pillar,
  AutoGeneratedPost,
  ValidationResult,
  VisualSuggestion,
} from "@/lib/api";

const statusConfig: Record<string, { label: string; className: string }> = {
  draft: { label: "Brouillon", className: "bg-gray-100 text-gray-700" },
  review: { label: "En revue", className: "bg-yellow-100 text-yellow-700" },
  approved: { label: "Approuvé", className: "bg-blue-100 text-blue-700" },
  scheduled: { label: "Planifié", className: "bg-purple-100 text-purple-700" },
  published: { label: "Publié", className: "bg-green-100 text-green-700" },
  failed: { label: "Échoué", className: "bg-red-100 text-red-700" },
};

function ValidationBadge({ score }: { score: number }) {
  const color =
    score >= 80
      ? "bg-green-100 text-green-700"
      : score >= 50
        ? "bg-yellow-100 text-yellow-700"
        : "bg-red-100 text-red-700";
  return <Badge className={color}>Anti-IA: {score}</Badge>;
}

// ─── Generate Dialog ─────────────────────────────────────────
function GenerateDialog({
  defaultTopic,
  defaultIdeaId,
  onOpenChange,
  externalOpen,
  onGenerated,
}: {
  defaultTopic?: string;
  defaultIdeaId?: string;
  onOpenChange?: (open: boolean) => void;
  externalOpen?: boolean;
  onGenerated?: () => void;
}) {
  const [topic, setTopic] = useState(defaultTopic || "");
  const [generating, setGenerating] = useState(false);
  const [result, setResult] = useState<AutoGeneratedPost | null>(null);
  const [editedContent, setEditedContent] = useState("");
  const [revalidation, setRevalidation] = useState<ValidationResult | null>(null);
  const [open, setOpen] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const isOpen = externalOpen !== undefined ? externalOpen : open;
  const handleOpenChange = (v: boolean) => {
    setOpen(v);
    onOpenChange?.(v);
    if (!v && result) onGenerated?.();
  };

  useEffect(() => {
    if (isOpen && defaultTopic) {
      setTopic(defaultTopic);
      setResult(null);
      setError(null);
      setRevalidation(null);
    }
  }, [isOpen, defaultTopic]);

  const handleGenerate = async () => {
    if (!topic.trim()) return;
    setGenerating(true);
    setResult(null);
    setRevalidation(null);
    setError(null);
    try {
      const generated = await api.generateAutoPost({
        topic: topic.trim(),
        idea_id: defaultIdeaId,
        save_as_draft: true,
      });
      setResult(generated);
      setEditedContent(generated.content);
    } catch (err) {
      setError(err instanceof Error ? err.message : "Erreur de génération");
    } finally {
      setGenerating(false);
    }
  };

  const handleRevalidate = async () => {
    if (!editedContent) return;
    const validation = await api.validatePost(editedContent);
    setRevalidation(validation);
  };

  const handleSaveEdit = async () => {
    if (!result?.post_id || !editedContent) return;
    await api.updatePost(result.post_id, { content: editedContent });
    if (revalidation) await handleRevalidate();
  };

  const dialogContent = (
    <DialogContent className="max-w-[680px] w-full max-h-[95vh] overflow-y-auto">
      <DialogHeader>
        <DialogTitle>Générer un post LinkedIn</DialogTitle>
      </DialogHeader>
      <div className="space-y-4 pt-2">
        <div>
          <label className="text-sm font-medium text-gray-700 mb-1 block">
            De quoi voulez-vous parler ?
          </label>
          <Textarea
            placeholder="Ex: Parler du fait que 80% des LP n'ont pas de message match, raconter comment un client a doublé son CR..."
            value={topic}
            onChange={(e) => setTopic(e.target.value)}
            className="min-h-[100px]"
            onKeyDown={(e) => { if (e.key === "Enter" && e.metaKey) handleGenerate(); }}
          />
          <p className="text-xs text-gray-400 mt-1">
            L&apos;IA choisit automatiquement le meilleur pilier et template. Cmd+Enter pour lancer.
          </p>
        </div>
        <Button onClick={handleGenerate} disabled={!topic.trim() || generating} className="w-full">
          {generating ? (
            <span className="flex items-center gap-2">
              <svg className="animate-spin h-4 w-4" viewBox="0 0 24 24">
                <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" fill="none" />
                <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4z" />
              </svg>
              L&apos;IA analyse et génère...
            </span>
          ) : "Générer le post"}
        </Button>
        {error && <div className="bg-red-50 text-red-700 rounded px-4 py-3 text-sm">{error}</div>}
        {result && (
          <div className="space-y-4 border-t pt-4">
            <div className="bg-blue-50 rounded-lg px-4 py-3 space-y-1">
              <div className="flex items-center gap-2 flex-wrap">
                <Badge className="bg-blue-100 text-blue-700">{result.pillar_name}</Badge>
                <Badge className="bg-indigo-100 text-indigo-700">{result.template_name}</Badge>
                <ValidationBadge score={(revalidation || result.validation).score} />
                {result.post_id && <Badge variant="outline">Sauvé en brouillon</Badge>}
              </div>
              <p className="text-xs text-blue-600 mt-1">{result.reasoning}</p>
            </div>
            <Textarea
              value={editedContent}
              onChange={(e) => setEditedContent(e.target.value)}
              className="min-h-[400px] text-[14px] leading-[1.42] text-gray-900 border-gray-200"
              style={{ fontFamily: '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif' }}
            />
            <div className="flex gap-2 flex-wrap">
              <Button variant="outline" onClick={handleRevalidate} size="sm">Re-valider anti-IA</Button>
              <Button variant="outline" onClick={handleSaveEdit} size="sm" disabled={editedContent === result.content}>
                Sauvegarder
              </Button>
              <Button onClick={handleGenerate} variant="outline" size="sm" disabled={generating}>Regénérer</Button>
            </div>
            {(revalidation || result.validation).issues.length > 0 && (
              <div className="space-y-2">
                <h4 className="text-sm font-medium text-gray-700">Validation anti-IA</h4>
                {(revalidation || result.validation).issues.map((issue, i) => (
                  <div key={i} className={`text-sm rounded px-3 py-2 ${issue.severity === "error" ? "bg-red-50 text-red-700" : "bg-yellow-50 text-yellow-700"}`}>
                    <span className="font-medium">{issue.rule}</span>
                    <span className="block text-xs mt-0.5">{issue.detail}</span>
                  </div>
                ))}
              </div>
            )}
          </div>
        )}
      </div>
    </DialogContent>
  );

  if (externalOpen !== undefined) {
    return <Dialog open={isOpen} onOpenChange={handleOpenChange}>{dialogContent}</Dialog>;
  }
  return (
    <Dialog open={isOpen} onOpenChange={handleOpenChange}>
      <DialogTrigger className="inline-flex items-center justify-center gap-2 whitespace-nowrap rounded-md text-sm font-medium bg-primary text-primary-foreground shadow-xs hover:bg-primary/90 h-9 px-4 py-2">
        Générer avec IA
      </DialogTrigger>
      {dialogContent}
    </Dialog>
  );
}

// ─── Visual Suggestion Panel ─────────────────────────────────
function VisualSuggestionPanel({ post, pillarName }: { post: Post; pillarName: string }) {
  const [suggestion, setSuggestion] = useState<VisualSuggestion | null>(null);
  const [loading, setLoading] = useState(false);
  const [loaded, setLoaded] = useState(false);

  const loadSuggestion = async () => {
    setLoading(true);
    try {
      const result = await api.suggestVisual(post.content, pillarName);
      setSuggestion(result);
      setLoaded(true);
    } catch {
      setSuggestion(null);
    } finally {
      setLoading(false);
    }
  };

  if (!loaded) {
    return (
      <button
        onClick={loadSuggestion}
        disabled={loading}
        className="text-xs text-blue-600 hover:text-blue-800 flex items-center gap-1 mt-2"
      >
        {loading ? (
          <><svg className="animate-spin h-3 w-3" viewBox="0 0 24 24"><circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" fill="none" /><path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4z" /></svg> Analyse du visuel...</>
        ) : (
          <><span>🎨</span> Suggérer un visuel</>
        )}
      </button>
    );
  }

  if (!suggestion) return null;

  const typeIcons: Record<string, string> = {
    carousel: "📑 Carrousel PDF",
    image: "🖼️ Image statique",
    text_only: "📝 Texte seul",
  };

  return (
    <div className="mt-3 bg-gradient-to-r from-purple-50 to-blue-50 rounded-lg p-3 border border-purple-100">
      <div className="flex items-center gap-2 mb-1">
        <Badge className="bg-purple-100 text-purple-700 text-xs">
          {typeIcons[suggestion.visual_type] || suggestion.visual_type}
        </Badge>
        <span className="text-xs text-gray-500">{suggestion.reasoning}</span>
      </div>
      <p className="text-sm text-gray-700 mt-1">{suggestion.visual_description}</p>
      {suggestion.carousel_slides && suggestion.carousel_slides.length > 0 && (
        <div className="mt-2 space-y-1">
          <p className="text-xs font-medium text-purple-700">Plan du carrousel :</p>
          <div className="flex gap-2 overflow-x-auto pb-1">
            {suggestion.carousel_slides.map((slide) => (
              <div key={slide.slide_number} className="flex-shrink-0 w-36 bg-white rounded p-2 border border-purple-100 shadow-sm">
                <p className="text-xs font-medium text-gray-800 truncate">#{slide.slide_number} {slide.title}</p>
                <p className="text-xs text-gray-500 line-clamp-2 mt-0.5">{slide.content}</p>
              </div>
            ))}
          </div>
        </div>
      )}
    </div>
  );
}

// ─── Post Editor ─────────────────────────────────────────────
function PostEditor({
  post,
  pillarName,
  onSaved,
  onClose,
}: {
  post: Post;
  pillarName: string;
  onSaved: () => void;
  onClose: () => void;
}) {
  const [content, setContent] = useState(post.content);
  const [saving, setSaving] = useState(false);
  const [validation, setValidation] = useState<ValidationResult | null>(null);

  const handleSave = async () => {
    setSaving(true);
    try {
      await api.updatePost(post.id, { content });
      onSaved();
    } catch (err) {
      console.error(err);
    } finally {
      setSaving(false);
    }
  };

  const handleValidate = async () => {
    const result = await api.validatePost(content);
    setValidation(result);
  };

  const handleApprove = async () => {
    await api.updatePost(post.id, { content, status: "approved" });
    onSaved();
  };

  const handleDelete = async () => {
    if (!confirm("Supprimer ce post ?")) return;
    await api.deletePost(post.id);
    onSaved();
  };

  const wordCount = content.split(/\s+/).filter(Boolean).length;

  return (
    <Dialog open onOpenChange={(open) => { if (!open) onClose(); }}>
      <DialogContent className="max-w-[680px] w-full max-h-[95vh] overflow-y-auto p-0">
        {/* LinkedIn-style header */}
        <div className="sticky top-0 bg-white z-10 border-b px-6 py-3 flex items-center justify-between">
          <div className="flex items-center gap-2 flex-wrap">
            <Badge className={statusConfig[post.status]?.className}>{statusConfig[post.status]?.label}</Badge>
            {pillarName && <Badge className="bg-blue-100 text-blue-700">{pillarName}</Badge>}
            {post.anti_ai_score !== null && <ValidationBadge score={post.anti_ai_score} />}
            <span className="text-xs text-gray-400">{wordCount} mots</span>
          </div>
        </div>

        {/* LinkedIn-style post preview / editor */}
        <div className="px-6 py-4">
          {/* Author header — LinkedIn style */}
          <div className="flex items-center gap-3 mb-4">
            <div className="w-12 h-12 bg-blue-600 rounded-full flex items-center justify-center text-white font-bold text-lg shrink-0">
              ST
            </div>
            <div>
              <p className="font-semibold text-gray-900 text-[15px] leading-tight">Sébastien Tortu</p>
              <p className="text-xs text-gray-500 leading-tight">Fondateur Boost Conversion | Expert CRO & Post-Clic</p>
              <p className="text-xs text-gray-400">Maintenant</p>
            </div>
          </div>

          {/* Content editor — LinkedIn feed width */}
          <Textarea
            value={content}
            onChange={(e) => setContent(e.target.value)}
            className="w-full min-h-[450px] border-0 shadow-none focus-visible:ring-0 text-[14px] leading-[1.42] text-gray-900 resize-none p-0 placeholder:text-gray-400"
            style={{ fontFamily: '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif' }}
          />

          {/* LinkedIn-style engagement bar */}
          <div className="border-t mt-4 pt-3 flex items-center gap-6 text-gray-500 text-xs">
            <span>👍 J&apos;aime</span>
            <span>💬 Commenter</span>
            <span>🔄 Republier</span>
            <span>📤 Envoyer</span>
          </div>
        </div>

        {/* Action bar */}
        <div className="border-t px-6 py-3 flex gap-2 flex-wrap bg-gray-50">
          <Button onClick={handleSave} disabled={saving || content === post.content} size="sm">
            {saving ? "Sauvegarde..." : "Sauvegarder"}
          </Button>
          <Button variant="outline" onClick={handleValidate} size="sm">
            Valider anti-IA
          </Button>
          {post.status === "draft" && (
            <Button variant="outline" onClick={handleApprove} size="sm" className="text-green-700 border-green-300 hover:bg-green-50">
              Approuver
            </Button>
          )}
          <Button variant="outline" onClick={handleDelete} size="sm" className="text-red-500 border-red-200 hover:bg-red-50 ml-auto">
            Supprimer
          </Button>
        </div>

        {/* Validation results */}
        {validation && (
          <div className="px-6 py-3 border-t space-y-2">
            <div className="flex items-center gap-2">
              <h4 className="text-sm font-medium">Validation anti-IA</h4>
              <ValidationBadge score={validation.score} />
            </div>
            {validation.issues.length === 0 ? (
              <p className="text-sm text-green-600">Aucun problème. Le post semble naturel.</p>
            ) : (
              validation.issues.map((issue, i) => (
                <div key={i} className={`text-sm rounded px-3 py-2 ${issue.severity === "error" ? "bg-red-50 text-red-700" : "bg-yellow-50 text-yellow-700"}`}>
                  <span className="font-medium">{issue.rule}</span>
                  <span className="block text-xs mt-0.5">{issue.detail}</span>
                  </div>
                ))
              )}
          </div>
        )}
      </DialogContent>
    </Dialog>
  );
}

// ─── Post Card ───────────────────────────────────────────────
function PostCard({
  post,
  pillarName,
  onEdit,
  onRefresh,
}: {
  post: Post;
  pillarName: string;
  onEdit: () => void;
  onRefresh: () => void;
}) {
  const status = statusConfig[post.status] || statusConfig.draft;

  const handleApprove = async () => {
    await api.updatePost(post.id, { status: "approved" });
    onRefresh();
  };

  return (
    <Card className="hover:shadow-md transition-shadow h-full flex flex-col">
      <CardContent className="p-4 flex flex-col flex-1">
        <div className="flex items-center gap-1.5 mb-2 flex-wrap">
          <Badge className={`${status.className} text-[10px] px-1.5 py-0`}>{status.label}</Badge>
          {pillarName && (
            <Badge className="bg-blue-50 text-blue-600 text-[10px] px-1.5 py-0">{pillarName}</Badge>
          )}
          {post.anti_ai_score !== null && <ValidationBadge score={post.anti_ai_score} />}
        </div>

        {/* Hook highlight */}
        {post.hook && (
          <p className="text-sm font-semibold text-gray-900 mb-1 line-clamp-2">{post.hook}</p>
        )}

        {/* Body preview */}
        <p className="text-xs text-gray-600 line-clamp-4 whitespace-pre-wrap flex-1">
          {post.hook ? post.content.replace(post.hook, "").trim().substring(0, 200) : post.content.substring(0, 200)}
        </p>

        <div className="mt-3 pt-2 border-t flex items-center justify-between">
          <span className="text-[10px] text-gray-400">
            {new Date(post.created_at).toLocaleDateString("fr-FR", { day: "numeric", month: "short" })}
            {post.word_count ? ` · ${post.word_count} mots` : ""}
          </span>
          <div className="flex gap-1.5">
            {post.status === "draft" && (
              <Button size="sm" variant="ghost" onClick={handleApprove}
                className="text-green-700 hover:bg-green-50 h-7 text-xs px-2">
                ✓
              </Button>
            )}
            <Button variant="outline" size="sm" onClick={onEdit} className="h-7 text-xs px-2">
              Éditer
            </Button>
          </div>
        </div>

        {/* Visual suggestion */}
        <VisualSuggestionPanel post={post} pillarName={pillarName} />
      </CardContent>
    </Card>
  );
}

// ─── Main Posts Content ──────────────────────────────────────
function PostsContent() {
  const [posts, setPosts] = useState<Post[]>([]);
  const [pillars, setPillars] = useState<Pillar[]>([]);
  const [loading, setLoading] = useState(true);
  const [tab, setTab] = useState("all");
  const [pillarFilter, setPillarFilter] = useState<string>("all");
  const [editingPost, setEditingPost] = useState<Post | null>(null);
  const searchParams = useSearchParams();

  const ideaTopic = searchParams.get("topic");
  const ideaId = searchParams.get("idea_id");
  const [autoGenerateOpen, setAutoGenerateOpen] = useState(!!ideaTopic);

  const pillarMap = Object.fromEntries(pillars.map((p) => [p.id, p.name]));

  const loadPosts = useCallback(() => {
    const params: Record<string, string> = {};
    if (tab !== "all") params.status = tab;
    if (pillarFilter !== "all") params.pillar_id = pillarFilter;
    setLoading(true);
    api.listPosts(Object.keys(params).length ? params : undefined)
      .then(setPosts)
      .catch(console.error)
      .finally(() => setLoading(false));
  }, [tab, pillarFilter]);

  useEffect(() => { api.listPillars().then(setPillars).catch(console.error); }, []);
  useEffect(() => { loadPosts(); }, [loadPosts]);

  const filteredPosts = pillarFilter === "all"
    ? posts
    : posts.filter((p) => p.pillar_id === pillarFilter);

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <h1 className="text-2xl font-bold text-gray-900">Posts</h1>
        <GenerateDialog onGenerated={loadPosts} />
      </div>

      {ideaTopic && (
        <GenerateDialog
          defaultTopic={ideaTopic}
          defaultIdeaId={ideaId || undefined}
          externalOpen={autoGenerateOpen}
          onOpenChange={setAutoGenerateOpen}
          onGenerated={loadPosts}
        />
      )}

      {/* Filters bar */}
      <div className="flex gap-4 items-center flex-wrap">
        <Tabs value={tab} onValueChange={setTab}>
          <TabsList>
            <TabsTrigger value="all">Tous</TabsTrigger>
            <TabsTrigger value="draft">Brouillons</TabsTrigger>
            <TabsTrigger value="approved">Approuvés</TabsTrigger>
            <TabsTrigger value="scheduled">Planifiés</TabsTrigger>
            <TabsTrigger value="published">Publiés</TabsTrigger>
          </TabsList>
        </Tabs>

        {/* Pillar filter */}
        <div className="flex gap-1.5 flex-wrap">
          <button
            onClick={() => setPillarFilter("all")}
            className={`px-2.5 py-1 rounded-full text-xs font-medium transition-colors ${
              pillarFilter === "all" ? "bg-gray-900 text-white" : "bg-gray-100 text-gray-600 hover:bg-gray-200"
            }`}
          >
            Tous les piliers
          </button>
          {pillars.map((p) => (
            <button
              key={p.id}
              onClick={() => setPillarFilter(p.id)}
              className={`px-2.5 py-1 rounded-full text-xs font-medium transition-colors ${
                pillarFilter === p.id ? "bg-blue-600 text-white" : "bg-blue-50 text-blue-700 hover:bg-blue-100"
              }`}
            >
              {p.name}
            </button>
          ))}
        </div>
      </div>

      {/* Posts grid — 3 columns */}
      {loading ? (
        <p className="text-sm text-gray-500 text-center py-8">Chargement...</p>
      ) : filteredPosts.length === 0 ? (
        <Card>
          <CardContent className="p-6">
            <p className="text-sm text-gray-500 text-center py-8">
              Aucun post. Cliquez sur &quot;Générer avec IA&quot; pour créer votre premier post.
            </p>
          </CardContent>
        </Card>
      ) : (
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
          {filteredPosts.map((post) => (
            <PostCard
              key={post.id}
              post={post}
              pillarName={pillarMap[post.pillar_id || ""] || ""}
              onEdit={() => setEditingPost(post)}
              onRefresh={loadPosts}
            />
          ))}
        </div>
      )}

      {/* Editor dialog */}
      {editingPost && (
        <PostEditor
          post={editingPost}
          pillarName={pillarMap[editingPost.pillar_id || ""] || ""}
          onSaved={() => { setEditingPost(null); loadPosts(); }}
          onClose={() => setEditingPost(null)}
        />
      )}
    </div>
  );
}

export default function PostsPage() {
  return (
    <Suspense fallback={<p className="text-sm text-gray-500 text-center py-8">Chargement...</p>}>
      <PostsContent />
    </Suspense>
  );
}
