"""add products table

Revision ID: eb6738bc4ceb
Revises: 75f76d236695
Create Date: 2026-03-16 21:07:40.848250

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'eb6738bc4ceb'
down_revision: Union[str, None] = '75f76d236695'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('tagline', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('target_audience', sa.Text(), nullable=False),
    sa.Column('key_benefits', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('pain_points', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('proof_points', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('cta_text', sa.String(length=500), nullable=True),
    sa.Column('price_info', sa.String(length=255), nullable=True),
    sa.Column('url', sa.String(length=1024), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('slug')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('products')
    # ### end Alembic commands ###
