"use client";

import { useEffect, useState, useMemo } from "react";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Textarea } from "@/components/ui/textarea";
import { Input } from "@/components/ui/input";
import { Badge } from "@/components/ui/badge";
import { Tabs, TabsList, TabsTrigger } from "@/components/ui/tabs";
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import { api, Idea, Pillar, AutoGeneratedPost, ValidationResult } from "@/lib/api";

const priorityConfig: Record<string, { label: string; className: string; order: number }> = {
  high: { label: "Haute", className: "bg-red-100 text-red-700", order: 0 },
  medium: { label: "Moyenne", className: "bg-yellow-100 text-yellow-700", order: 1 },
  low: { label: "Basse", className: "bg-gray-100 text-gray-700", order: 2 },
};

const statusConfig: Record<string, { label: string; className: string }> = {
  new: { label: "Nouvelle", className: "bg-blue-100 text-blue-700" },
  drafting: { label: "En rédaction", className: "bg-yellow-100 text-yellow-700" },
  planned: { label: "Planifiée", className: "bg-purple-100 text-purple-700" },
  published: { label: "Publiée", className: "bg-green-100 text-green-700" },
  archived: { label: "Archivée", className: "bg-gray-100 text-gray-500" },
};

type SortMode = "priority" | "recent" | "pillar";

const Spinner = () => (
  <svg className="animate-spin h-4 w-4" viewBox="0 0 24 24">
    <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" fill="none" />
    <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4z" />
  </svg>
);

// ─── Generate From Idea Dialog ───────────────────────────────
function GenerateFromIdeaDialog({
  idea,
  open,
  onOpenChange,
  onGenerated,
}: {
  idea: Idea;
  open: boolean;
  onOpenChange: (open: boolean) => void;
  onGenerated: () => void;
}) {
  const [generating, setGenerating] = useState(false);
  const [result, setResult] = useState<AutoGeneratedPost | null>(null);
  const [editedContent, setEditedContent] = useState("");
  const [error, setError] = useState<string | null>(null);
  const [revalidation, setRevalidation] = useState<ValidationResult | null>(null);

  const handleGenerate = async () => {
    setGenerating(true);
    setResult(null);
    setError(null);
    setRevalidation(null);
    try {
      const generated = await api.generateAutoPost({
        topic: idea.raw_input,
        source_url: idea.source_url || undefined,
        idea_id: idea.id,
        save_as_draft: true,
      });
      setResult(generated);
      setEditedContent(generated.content);
    } catch (err) {
      setError(err instanceof Error ? err.message : "Erreur de génération");
    } finally {
      setGenerating(false);
    }
  };

  const handleRevalidate = async () => {
    if (!editedContent) return;
    const validation = await api.validatePost(editedContent);
    setRevalidation(validation);
  };

  const handleSaveEdit = async () => {
    if (!result?.post_id || !editedContent) return;
    await api.updatePost(result.post_id, { content: editedContent });
  };

  useEffect(() => {
    if (open && !result && !generating) handleGenerate();
  }, [open]);

  const validation = revalidation || result?.validation;

  return (
    <Dialog open={open} onOpenChange={(v) => { onOpenChange(v); if (!v && result) onGenerated(); }}>
      <DialogContent className="max-w-[680px] w-full max-h-[95vh] overflow-y-auto">
        <DialogHeader>
          <DialogTitle>Générer un post depuis cette idée</DialogTitle>
        </DialogHeader>
        <div className="space-y-4 pt-2">
          <div className="bg-gray-50 rounded-lg px-4 py-3">
            <p className="text-xs font-medium text-gray-500 mb-1">Idée originale</p>
            <p className="text-sm text-gray-800 whitespace-pre-wrap">{idea.raw_input}</p>
            {idea.source_url && (
              <a href={idea.source_url} target="_blank" rel="noopener noreferrer"
                className="text-xs text-blue-500 hover:underline mt-1 block">{idea.source_url}</a>
            )}
          </div>
          {generating && (
            <div className="flex items-center justify-center py-8 gap-3">
              <Spinner />
              <p className="text-sm text-gray-600">L&apos;IA analyse, choisit le format et génère le post...</p>
            </div>
          )}
          {error && (
            <div className="bg-red-50 text-red-700 rounded px-4 py-3 text-sm">
              {error}
              <Button variant="outline" size="sm" className="mt-2" onClick={handleGenerate}>Réessayer</Button>
            </div>
          )}
          {result && (
            <div className="space-y-4">
              <div className="bg-blue-50 rounded-lg px-4 py-3 space-y-1">
                <div className="flex items-center gap-2 flex-wrap">
                  <Badge className="bg-blue-100 text-blue-700">{result.pillar_name}</Badge>
                  <Badge className="bg-indigo-100 text-indigo-700">{result.template_name}</Badge>
                  {validation && (
                    <Badge className={validation.score >= 80 ? "bg-green-100 text-green-700" : validation.score >= 50 ? "bg-yellow-100 text-yellow-700" : "bg-red-100 text-red-700"}>
                      Anti-IA: {validation.score}/100
                    </Badge>
                  )}
                  {result.post_id && <Badge variant="outline">Sauvé en brouillon</Badge>}
                </div>
                <p className="text-xs text-blue-600 mt-1">{result.reasoning}</p>
              </div>
              <Textarea value={editedContent} onChange={(e) => setEditedContent(e.target.value)}
                className="min-h-[400px] text-[14px] leading-[1.42] text-gray-900 border-gray-200"
                style={{ fontFamily: '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif' }}
              />
              <div className="flex gap-2 flex-wrap">
                <Button variant="outline" onClick={handleRevalidate} size="sm">Re-valider anti-IA</Button>
                <Button variant="outline" onClick={handleSaveEdit} size="sm" disabled={editedContent === result.content}>Sauvegarder</Button>
                <Button onClick={handleGenerate} variant="outline" size="sm" disabled={generating}>Regénérer</Button>
              </div>
              {validation && validation.issues.length > 0 && (
                <div className="space-y-2">
                  {validation.issues.map((issue, i) => (
                    <div key={i} className={`text-sm rounded px-3 py-2 ${issue.severity === "error" ? "bg-red-50 text-red-700" : "bg-yellow-50 text-yellow-700"}`}>
                      <span className="font-medium">{issue.rule}</span>
                      <span className="block text-xs mt-0.5">{issue.detail}</span>
                    </div>
                  ))}
                </div>
              )}
            </div>
          )}
        </div>
      </DialogContent>
    </Dialog>
  );
}

// ─── Brief Ideas Dialog (generate multiple angles from one brief) ───
type BriefIdea = {
  title: string;
  description: string;
  pillar_name: string;
  template_name: string;
  hook_preview: string;
  priority: string;
  tags: string[];
  channel: string;
};

function BriefDialog({
  open,
  onOpenChange,
  onSaved,
}: {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  onSaved: () => void;
}) {
  const [brief, setBrief] = useState("");
  const [channel, setChannel] = useState<"linkedin" | "newsletter" | "both">("linkedin");
  const [generating, setGenerating] = useState(false);
  const [ideas, setIdeas] = useState<BriefIdea[]>([]);
  const [selected, setSelected] = useState<Set<number>>(new Set());
  const [saving, setSaving] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const handleGenerate = async () => {
    if (!brief.trim()) return;
    setGenerating(true);
    setIdeas([]);
    setSelected(new Set());
    setError(null);
    try {
      const result = await api.generateFromBrief({ brief: brief.trim(), count: 6, channel });
      setIdeas(result.ideas);
    } catch (err) {
      setError(err instanceof Error ? err.message : "Erreur");
    } finally {
      setGenerating(false);
    }
  };

  const toggleSelect = (i: number) => {
    const next = new Set(selected);
    if (next.has(i)) next.delete(i);
    else next.add(i);
    setSelected(next);
  };

  const handleSaveSelected = async () => {
    setSaving(true);
    try {
      await api.generateFromBrief({
        brief: brief.trim(),
        count: 6,
        channel,
        save_selected: Array.from(selected),
      });
      onSaved();
      onOpenChange(false);
    } finally {
      setSaving(false);
    }
  };

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="max-w-3xl w-full max-h-[95vh] overflow-y-auto">
        <DialogHeader>
          <DialogTitle>Générer des idées depuis un brief</DialogTitle>
        </DialogHeader>
        <div className="space-y-4 pt-2">
          <Textarea
            placeholder="Votre brief : un sujet, une observation, une stat, un fait... Ex: '80% des marques DTC gaspillent leur budget ads parce que leurs landing pages ne convertissent pas'"
            value={brief}
            onChange={(e) => setBrief(e.target.value)}
            className="min-h-[80px]"
          />
          <div className="flex items-center gap-3">
            <div className="flex gap-1.5">
              {(["linkedin", "newsletter", "both"] as const).map((ch) => (
                <button
                  key={ch}
                  onClick={() => setChannel(ch)}
                  className={`px-2.5 py-1 rounded-full text-xs font-medium ${channel === ch ? "bg-blue-600 text-white" : "bg-gray-100 text-gray-600 hover:bg-gray-200"}`}
                >
                  {ch === "linkedin" ? "LinkedIn" : ch === "newsletter" ? "Newsletter" : "Les deux"}
                </button>
              ))}
            </div>
            <Button onClick={handleGenerate} disabled={!brief.trim() || generating} size="sm">
              {generating ? <><Spinner /> Génération...</> : "Générer 6 angles"}
            </Button>
          </div>

          {error && <div className="bg-red-50 text-red-700 rounded px-4 py-3 text-sm">{error}</div>}

          {ideas.length > 0 && (
            <>
              <p className="text-xs text-gray-500">Cliquez sur les idées que vous voulez garder, puis sauvegardez.</p>
              <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
                {ideas.map((idea, i) => {
                  const isSelected = selected.has(i);
                  const prio = priorityConfig[idea.priority] || priorityConfig.medium;
                  return (
                    <button
                      key={i}
                      onClick={() => toggleSelect(i)}
                      className={`text-left p-3 rounded-lg border-2 transition-all ${isSelected ? "border-blue-500 bg-blue-50" : "border-gray-200 hover:border-gray-300"}`}
                    >
                      <div className="flex items-center gap-1.5 mb-1.5 flex-wrap">
                        <Badge className={`${prio.className} text-[10px] px-1.5 py-0`}>{prio.label}</Badge>
                        <Badge className="bg-blue-50 text-blue-600 text-[10px] px-1.5 py-0">{idea.pillar_name}</Badge>
                        <Badge className="bg-indigo-50 text-indigo-600 text-[10px] px-1.5 py-0">{idea.template_name}</Badge>
                        {idea.channel === "newsletter" && <Badge className="bg-purple-50 text-purple-600 text-[10px] px-1.5 py-0">Newsletter</Badge>}
                        {isSelected && <Badge className="bg-blue-500 text-white text-[10px] px-1.5 py-0">Sélectionnée</Badge>}
                      </div>
                      <p className="text-sm font-semibold text-gray-900">{idea.title}</p>
                      <p className="text-xs text-gray-600 mt-1 line-clamp-2">{idea.description}</p>
                      {idea.hook_preview && (
                        <div className="mt-2 bg-gray-50 rounded px-2 py-1.5">
                          <p className="text-[10px] font-medium text-gray-500">Accroche</p>
                          <p className="text-xs text-gray-800 italic line-clamp-2">&quot;{idea.hook_preview}&quot;</p>
                        </div>
                      )}
                    </button>
                  );
                })}
              </div>
              <div className="flex items-center gap-3">
                <Button onClick={handleSaveSelected} disabled={selected.size === 0 || saving} size="sm">
                  {saving ? "Sauvegarde..." : `Sauvegarder ${selected.size} idée(s)`}
                </Button>
                <Button variant="outline" size="sm" onClick={() => { setSelected(new Set(ideas.map((_, i) => i))); }}>
                  Tout sélectionner
                </Button>
                <span className="text-xs text-gray-400">{selected.size}/{ideas.length} sélectionnées</span>
              </div>
            </>
          )}
        </div>
      </DialogContent>
    </Dialog>
  );
}

// ─── Web Research Dialog ─────────────────────────────────────
type ResearchIdea = {
  title: string;
  description: string;
  pillar_name: string;
  template_name: string;
  priority: string;
  tags: string[];
  source_urls: string[];
  research_insight: string;
};

function WebResearchDialog({
  open,
  onOpenChange,
  onDone,
}: {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  onDone: () => void;
}) {
  const [searching, setSearching] = useState(false);
  const [ideas, setIdeas] = useState<ResearchIdea[]>([]);
  const [selected, setSelected] = useState<Set<number>>(new Set());
  const [error, setError] = useState<string | null>(null);
  const [saving, setSaving] = useState(false);
  const [savedCount, setSavedCount] = useState(0);

  const handleSearch = async () => {
    setSearching(true);
    setIdeas([]);
    setSelected(new Set());
    setError(null);
    setSavedCount(0);
    try {
      const result = await api.webResearch({ num_queries: 4, ideas_count: 3, save: false });
      setIdeas(result.ideas);
    } catch (err) {
      setError(err instanceof Error ? err.message : "Erreur de recherche");
    } finally {
      setSearching(false);
    }
  };

  const toggleSelect = (i: number) => {
    const next = new Set(selected);
    if (next.has(i)) next.delete(i);
    else next.add(i);
    setSelected(next);
  };

  const handleSaveSelected = async () => {
    if (selected.size === 0) return;
    setSaving(true);
    try {
      const toSave = Array.from(selected).map((i) => ideas[i]);
      // Save each selected idea via createIdea
      for (const idea of toSave) {
        await api.createIdea({
          input_type: "raw_idea",
          raw_input: `${idea.title}\n\n${idea.description}${idea.research_insight ? `\n\nInsight: ${idea.research_insight}` : ""}`,
          source_url: idea.source_urls?.[0] || undefined,
        });
      }
      setSavedCount(toSave.length);
      onDone();
    } finally {
      setSaving(false);
    }
  };

  useEffect(() => {
    if (open && ideas.length === 0 && !searching) handleSearch();
  }, [open]);

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="max-w-3xl w-full max-h-[95vh] overflow-y-auto">
        <DialogHeader>
          <DialogTitle>Veille web — Recherche de sujets CRO</DialogTitle>
        </DialogHeader>
        <div className="space-y-4 pt-2">
          <p className="text-sm text-gray-600">
            L&apos;outil recherche sur le web les dernières tendances en CRO, landing pages, A/B testing et conversion e-commerce pour générer des idées de posts percutantes.
          </p>

          {searching && (
            <div className="flex items-center justify-center py-12 gap-3">
              <Spinner />
              <p className="text-sm text-gray-600">Recherche en cours sur le web + analyse IA...</p>
            </div>
          )}

          {error && (
            <div className="bg-red-50 text-red-700 rounded px-4 py-3 text-sm">
              {error}
              <Button variant="outline" size="sm" className="mt-2" onClick={handleSearch}>Réessayer</Button>
            </div>
          )}

          {ideas.length > 0 && (
            <>
              {savedCount > 0 && (
                <div className="bg-green-50 rounded-lg px-4 py-3 text-sm text-green-700">
                  {savedCount} idée(s) ajoutée(s) à votre boîte à idées.
                </div>
              )}
              {savedCount === 0 && (
                <p className="text-xs text-gray-500">Cliquez sur les idées que vous voulez garder, puis sauvegardez.</p>
              )}
              <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
                {ideas.map((idea, i) => {
                  const prio = priorityConfig[idea.priority] || priorityConfig.medium;
                  const isSelected = selected.has(i);
                  return (
                    <button
                      key={i}
                      onClick={() => toggleSelect(i)}
                      className={`text-left p-3 rounded-lg border-2 transition-all space-y-2 ${isSelected ? "border-blue-500 bg-blue-50" : "border-gray-200 hover:border-gray-300"}`}
                    >
                      <div className="flex items-center gap-1.5 flex-wrap">
                        <Badge className={`${prio.className} text-[10px] px-1.5 py-0`}>{prio.label}</Badge>
                        <Badge className="bg-blue-50 text-blue-600 text-[10px] px-1.5 py-0">{idea.pillar_name}</Badge>
                        <Badge className="bg-indigo-50 text-indigo-600 text-[10px] px-1.5 py-0">{idea.template_name}</Badge>
                        {isSelected && <Badge className="bg-blue-500 text-white text-[10px] px-1.5 py-0">Sélectionnée</Badge>}
                      </div>
                      <p className="text-sm font-semibold text-gray-900">{idea.title}</p>
                      <p className="text-xs text-gray-600 line-clamp-3">{idea.description}</p>
                      {idea.research_insight && (
                        <div className="bg-amber-50 rounded px-2 py-1.5">
                          <p className="text-[10px] font-medium text-amber-700">Insight web</p>
                          <p className="text-[10px] text-amber-600">{idea.research_insight}</p>
                        </div>
                      )}
                      {idea.source_urls && idea.source_urls.length > 0 && (
                        <div className="flex gap-1 flex-wrap">
                          {idea.source_urls.map((url, j) => (
                            <span key={j} className="text-[10px] text-blue-500 truncate max-w-[200px]">
                              {(() => { try { return new URL(url).hostname; } catch { return url; } })()}
                            </span>
                          ))}
                        </div>
                      )}
                    </button>
                  );
                })}
              </div>
              <div className="flex items-center gap-3">
                <Button onClick={handleSaveSelected} disabled={selected.size === 0 || saving} size="sm">
                  {saving ? "Sauvegarde..." : `Ajouter ${selected.size} idée(s)`}
                </Button>
                <Button variant="outline" size="sm" onClick={() => { setSelected(new Set(ideas.map((_, i) => i))); }}>
                  Tout sélectionner
                </Button>
                <Button variant="outline" size="sm" onClick={handleSearch} disabled={searching}>
                  {searching ? <><Spinner /> Recherche...</> : "Relancer"}
                </Button>
                <span className="text-xs text-gray-400">{selected.size}/{ideas.length} sélectionnées</span>
              </div>
            </>
          )}
        </div>
      </DialogContent>
    </Dialog>
  );
}

// ─── Idea Card ───────────────────────────────────────────────
function IdeaCard({
  idea,
  pillarName,
  onDelete,
  onArchive,
  onGenerate,
  onChangePriority,
}: {
  idea: Idea;
  pillarName: string;
  onDelete: (id: string) => void;
  onArchive: (id: string) => void;
  onGenerate: (idea: Idea) => void;
  onChangePriority: (id: string, priority: string) => void;
}) {
  const priority = priorityConfig[idea.priority] || priorityConfig.medium;
  const status = statusConfig[idea.status] || statusConfig.new;
  const title = idea.raw_input.split("\n")[0].substring(0, 80);
  const body = idea.raw_input.split("\n").slice(1).join("\n").trim();

  return (
    <Card className="hover:shadow-md transition-shadow h-full flex flex-col">
      <CardContent className="p-4 flex flex-col flex-1">
        <div className="flex items-center gap-1.5 mb-2 flex-wrap">
          <Badge className={`${status.className} text-[10px] px-1.5 py-0`}>{status.label}</Badge>
          <button onClick={() => {
            const priorities = ["high", "medium", "low"];
            const next = priorities[(priorities.indexOf(idea.priority) + 1) % 3];
            onChangePriority(idea.id, next);
          }}>
            <Badge className={`${priority.className} cursor-pointer hover:opacity-80 text-[10px] px-1.5 py-0`}>
              {priority.label}
            </Badge>
          </button>
          {pillarName && <Badge className="bg-blue-50 text-blue-600 text-[10px] px-1.5 py-0">{pillarName}</Badge>}
        </div>

        <p className="text-sm font-semibold text-gray-900 line-clamp-2">{title}</p>
        {body && <p className="text-xs text-gray-600 mt-1 line-clamp-3">{body}</p>}

        {idea.source_url && (
          <a href={idea.source_url} target="_blank" rel="noopener noreferrer"
            className="text-[10px] text-blue-500 hover:underline mt-1 block truncate">{idea.source_url}</a>
        )}

        {idea.suggested_angle && (
          <div className="mt-2 bg-blue-50 rounded px-2 py-1.5">
            <p className="text-[10px] font-medium text-blue-700">Angle suggéré</p>
            <p className="text-[10px] text-blue-600 line-clamp-2">{idea.suggested_angle}</p>
          </div>
        )}

        <div className="mt-auto pt-3 border-t flex items-center justify-between gap-1">
          <Button variant="default" size="sm" onClick={() => onGenerate(idea)} className="h-7 text-xs px-2">Rédiger</Button>
          <div className="flex gap-1">
            <Button variant="ghost" size="sm" onClick={() => onArchive(idea.id)} className="h-7 text-xs px-2 text-gray-500">Archiver</Button>
            <Button variant="ghost" size="sm" className="h-7 text-xs px-2 text-red-500 hover:text-red-700" onClick={() => onDelete(idea.id)}>✕</Button>
          </div>
        </div>
      </CardContent>
    </Card>
  );
}

// ─── Main Ideas Page ─────────────────────────────────────────
export default function IdeasPage() {
  const [ideas, setIdeas] = useState<Idea[]>([]);
  const [pillars, setPillars] = useState<Pillar[]>([]);
  const [loading, setLoading] = useState(true);
  const [tab, setTab] = useState("new");
  const [inputType, setInputType] = useState<"raw_idea" | "url">("raw_idea");
  const [inputValue, setInputValue] = useState("");
  const [sourceUrl, setSourceUrl] = useState("");
  const [submitting, setSubmitting] = useState(false);
  const [generatingIdea, setGeneratingIdea] = useState<Idea | null>(null);
  const [generatingBank, setGeneratingBank] = useState(false);
  const [bankResult, setBankResult] = useState<{ generated: number; saved: number } | null>(null);
  const [sortMode, setSortMode] = useState<SortMode>("priority");
  const [pillarFilter, setPillarFilter] = useState<string>("all");
  const [priorityFilter, setPriorityFilter] = useState<string>("all");

  // New dialogs
  const [briefOpen, setBriefOpen] = useState(false);
  const [webResearchOpen, setWebResearchOpen] = useState(false);
  const [watchRunning, setWatchRunning] = useState(false);
  const [watchResult, setWatchResult] = useState<{ generated: number; saved: number; sources_searched: string[] } | null>(null);

  const pillarMap = Object.fromEntries(pillars.map((p) => [p.id, p.name]));

  const loadIdeas = (status?: string) => {
    setLoading(true);
    const params = status && status !== "all" ? { status } : undefined;
    api.listIdeas(params).then(setIdeas).catch(console.error).finally(() => setLoading(false));
  };

  useEffect(() => { api.listPillars().then(setPillars).catch(console.error); }, []);
  useEffect(() => { loadIdeas(tab); }, [tab]);

  // Sort + filter
  const displayedIdeas = useMemo(() => {
    let filtered = [...ideas];
    if (pillarFilter !== "all") {
      filtered = filtered.filter((i) => i.suggested_pillar_id === pillarFilter);
    }
    if (priorityFilter !== "all") {
      filtered = filtered.filter((i) => i.priority === priorityFilter);
    }
    if (sortMode === "priority") {
      filtered.sort((a, b) => {
        const pa = priorityConfig[a.priority]?.order ?? 1;
        const pb = priorityConfig[b.priority]?.order ?? 1;
        return pa - pb;
      });
    }
    if (sortMode === "pillar") {
      filtered.sort((a, b) => {
        const na = pillarMap[a.suggested_pillar_id || ""] || "zzz";
        const nb = pillarMap[b.suggested_pillar_id || ""] || "zzz";
        return na.localeCompare(nb);
      });
    }
    return filtered;
  }, [ideas, sortMode, pillarFilter, priorityFilter, pillarMap]);

  // Counts
  const counts = useMemo(() => {
    const c: Record<string, number> = { all: ideas.length, high: 0, medium: 0, low: 0 };
    ideas.forEach((i) => { c[i.priority] = (c[i.priority] || 0) + 1; });
    return c;
  }, [ideas]);

  const handleSubmit = async () => {
    if (!inputValue.trim()) return;
    setSubmitting(true);
    try {
      await api.createIdea({
        input_type: inputType,
        raw_input: inputValue.trim(),
        source_url: inputType === "url" ? inputValue.trim() : sourceUrl || undefined,
      });
      setInputValue("");
      setSourceUrl("");
      loadIdeas(tab);
    } catch (err) {
      console.error(err);
    } finally {
      setSubmitting(false);
    }
  };

  const handleDelete = async (id: string) => {
    await api.deleteIdea(id);
    setIdeas(ideas.filter((i) => i.id !== id));
  };

  const handleArchive = async (id: string) => {
    await api.updateIdea(id, { status: "archived" } as Partial<Idea>);
    loadIdeas(tab);
  };

  const handleChangePriority = async (id: string, priority: string) => {
    await api.updateIdea(id, { priority } as Partial<Idea>);
    setIdeas(ideas.map((i) => (i.id === id ? { ...i, priority } : i)));
  };

  const handleGenerateBank = async () => {
    setGeneratingBank(true);
    setBankResult(null);
    try {
      const result = await api.generateIdeaBank({ count: 10, save: true });
      setBankResult({ generated: result.generated, saved: result.saved });
      loadIdeas(tab);
    } catch (err) {
      console.error(err);
    } finally {
      setGeneratingBank(false);
    }
  };

  const handleMultiWatch = async () => {
    setWatchRunning(true);
    setWatchResult(null);
    try {
      const result = await api.multiWatch({ save: true });
      setWatchResult({ generated: result.generated, saved: result.saved, sources_searched: result.sources_searched });
      loadIdeas(tab);
    } catch (err) {
      console.error(err);
    } finally {
      setWatchRunning(false);
    }
  };

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-2xl font-bold text-gray-900">Boîte à idées</h1>
          <p className="text-sm text-gray-500 mt-1">
            {ideas.length} idées — {counts.high} haute priorité, {counts.medium} moyenne, {counts.low} basse
          </p>
        </div>
        <div className="flex gap-2 flex-wrap">
          <Button onClick={() => setBriefOpen(true)} variant="outline" size="sm">
            Depuis un brief
          </Button>
          <Button onClick={() => setWebResearchOpen(true)} variant="outline" size="sm">
            Veille web
          </Button>
          <Button onClick={handleMultiWatch} disabled={watchRunning} variant="outline" size="sm" className="border-purple-300 text-purple-700 hover:bg-purple-50">
            {watchRunning ? <><Spinner /> Veille en cours...</> : "Veille multi-sources"}
          </Button>
          <Button onClick={handleGenerateBank} disabled={generatingBank} variant="outline" size="sm">
            {generatingBank ? <><Spinner /> Génération...</> : "Générer 10 idées IA"}
          </Button>
        </div>
      </div>

      {bankResult && (
        <div className="bg-green-50 rounded-lg px-4 py-3 text-sm text-green-700 flex items-center justify-between">
          <span>{bankResult.generated} idées générées et ajoutées.</span>
          <Button variant="ghost" size="sm" onClick={() => setBankResult(null)}>Fermer</Button>
        </div>
      )}

      {watchResult && (
        <div className="bg-purple-50 rounded-lg px-4 py-3 text-sm text-purple-700 flex items-center justify-between">
          <span>
            Veille terminée : {watchResult.generated} idées trouvées sur {watchResult.sources_searched.join(", ")}
          </span>
          <Button variant="ghost" size="sm" onClick={() => setWatchResult(null)}>Fermer</Button>
        </div>
      )}

      {/* Quick input */}
      <Card>
        <CardContent className="p-4 space-y-3">
          <div className="flex gap-2">
            <Button variant={inputType === "raw_idea" ? "default" : "outline"} size="sm" onClick={() => setInputType("raw_idea")}>
              Idée / thème
            </Button>
            <Button variant={inputType === "url" ? "default" : "outline"} size="sm" onClick={() => setInputType("url")}>
              URL de post
            </Button>
          </div>
          {inputType === "raw_idea" ? (
            <Textarea
              placeholder="Ex: Parler du fait que 80% des landing pages n'ont pas de message match..."
              className="min-h-[80px]"
              value={inputValue}
              onChange={(e) => setInputValue(e.target.value)}
              onKeyDown={(e) => { if (e.key === "Enter" && e.metaKey) handleSubmit(); }}
            />
          ) : (
            <Input type="url" placeholder="https://www.linkedin.com/posts/..."
              value={inputValue} onChange={(e) => setInputValue(e.target.value)}
              onKeyDown={(e) => { if (e.key === "Enter") handleSubmit(); }} />
          )}
          <div className="flex justify-between items-center">
            <span className="text-xs text-gray-400">{inputType === "raw_idea" ? "Cmd+Enter pour ajouter" : "Enter pour ajouter"}</span>
            <Button onClick={handleSubmit} disabled={!inputValue.trim() || submitting} size="sm">
              {submitting ? "Ajout..." : "Ajouter"}
            </Button>
          </div>
        </CardContent>
      </Card>

      {/* Filters & Sort */}
      <div className="space-y-3">
        <Tabs value={tab} onValueChange={setTab}>
          <TabsList>
            <TabsTrigger value="new">Nouvelles</TabsTrigger>
            <TabsTrigger value="drafting">En rédaction</TabsTrigger>
            <TabsTrigger value="planned">Planifiées</TabsTrigger>
            <TabsTrigger value="archived">Archivées</TabsTrigger>
          </TabsList>
        </Tabs>

        <div className="flex gap-4 items-center flex-wrap">
          {/* Sort */}
          <div className="flex items-center gap-1.5">
            <span className="text-xs text-gray-500">Trier :</span>
            {([["priority", "Priorité"], ["pillar", "Pilier"], ["recent", "Récent"]] as [SortMode, string][]).map(([mode, label]) => (
              <button
                key={mode}
                onClick={() => setSortMode(mode)}
                className={`px-2 py-0.5 rounded text-xs font-medium transition-colors ${
                  sortMode === mode ? "bg-gray-900 text-white" : "bg-gray-100 text-gray-600 hover:bg-gray-200"
                }`}
              >
                {label}
              </button>
            ))}
          </div>

          {/* Priority filter */}
          <div className="flex items-center gap-1.5">
            <span className="text-xs text-gray-500">Priorité :</span>
            <button
              onClick={() => setPriorityFilter("all")}
              className={`px-2 py-0.5 rounded text-xs font-medium ${priorityFilter === "all" ? "bg-gray-900 text-white" : "bg-gray-100 text-gray-600 hover:bg-gray-200"}`}
            >
              Toutes
            </button>
            {Object.entries(priorityConfig).map(([key, cfg]) => (
              <button
                key={key}
                onClick={() => setPriorityFilter(key)}
                className={`px-2 py-0.5 rounded text-xs font-medium ${priorityFilter === key ? cfg.className + " ring-1 ring-offset-1" : "bg-gray-100 text-gray-600 hover:bg-gray-200"}`}
              >
                {cfg.label} ({counts[key] || 0})
              </button>
            ))}
          </div>

          {/* Pillar filter */}
          <div className="flex items-center gap-1.5 flex-wrap">
            <span className="text-xs text-gray-500">Pilier :</span>
            <button
              onClick={() => setPillarFilter("all")}
              className={`px-2 py-0.5 rounded text-xs font-medium ${pillarFilter === "all" ? "bg-gray-900 text-white" : "bg-gray-100 text-gray-600 hover:bg-gray-200"}`}
            >
              Tous
            </button>
            {pillars.map((p) => (
              <button
                key={p.id}
                onClick={() => setPillarFilter(p.id)}
                className={`px-2 py-0.5 rounded text-xs font-medium ${pillarFilter === p.id ? "bg-blue-600 text-white" : "bg-blue-50 text-blue-700 hover:bg-blue-100"}`}
              >
                {p.name}
              </button>
            ))}
          </div>
        </div>
      </div>

      {/* Ideas grid — 3 columns */}
      {loading ? (
        <p className="text-sm text-gray-500 text-center py-8">Chargement...</p>
      ) : displayedIdeas.length === 0 ? (
        <Card>
          <CardContent className="p-6">
            <p className="text-sm text-gray-500 text-center py-8">
              {ideas.length === 0
                ? "Aucune idée. Ajoutez-en ou générez-en avec l'IA."
                : "Aucune idée ne correspond aux filtres sélectionnés."}
            </p>
          </CardContent>
        </Card>
      ) : (
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
          {displayedIdeas.map((idea) => (
            <IdeaCard
              key={idea.id}
              idea={idea}
              pillarName={pillarMap[idea.suggested_pillar_id || ""] || ""}
              onDelete={handleDelete}
              onArchive={handleArchive}
              onGenerate={(i) => setGeneratingIdea(i)}
              onChangePriority={handleChangePriority}
            />
          ))}
        </div>
      )}

      {/* Generate dialog */}
      {generatingIdea && (
        <GenerateFromIdeaDialog
          idea={generatingIdea}
          open={!!generatingIdea}
          onOpenChange={(open) => { if (!open) setGeneratingIdea(null); }}
          onGenerated={() => loadIdeas(tab)}
        />
      )}

      {/* Brief dialog */}
      <BriefDialog
        open={briefOpen}
        onOpenChange={setBriefOpen}
        onSaved={() => loadIdeas(tab)}
      />

      {/* Web Research dialog */}
      <WebResearchDialog
        open={webResearchOpen}
        onOpenChange={setWebResearchOpen}
        onDone={() => loadIdeas(tab)}
      />
    </div>
  );
}
