const API_BASE = process.env.NEXT_PUBLIC_API_URL || "http://localhost:8000/api";

export interface Pillar {
  id: string;
  name: string;
  description: string;
  weight: number;
  preferred_templates: string | null;
  display_order: number;
  is_active: boolean;
}

export interface PostTemplate {
  id: string;
  name: string;
  slug: string;
  description: string;
  structure: { steps: { name: string; description: string }[] };
  example_posts: Record<string, unknown> | null;
  prompt_instructions: string;
  when_to_use: string;
  display_order: number;
  is_active: boolean;
}

export interface WritingRule {
  id: string;
  category: string;
  name: string;
  content: string;
  example_good: string | null;
  example_bad: string | null;
  severity: string;
  display_order: number;
  is_active: boolean;
}

export interface Post {
  id: string;
  content: string;
  hook: string | null;
  format: string;
  pillar_id: string | null;
  template_id: string | null;
  idea_id: string | null;
  hook_pattern: string | null;
  cta_type: string | null;
  word_count: number | null;
  image_url: string | null;
  status: string;
  scheduled_at: string | null;
  published_at: string | null;
  anti_ai_score: number | null;
  anti_ai_issues: Record<string, unknown>[] | null;
  created_at: string;
  updated_at: string;
}

export interface Idea {
  id: string;
  input_type: string;
  raw_input: string;
  source_url: string | null;
  scraped_content: string | null;
  suggested_pillar_id: string | null;
  suggested_template_id: string | null;
  suggested_angle: string | null;
  priority: string;
  tags: Record<string, unknown> | null;
  status: string;
}

export interface ValidationResult {
  score: number;
  issues: { rule: string; severity: string; detail: string }[];
  passed: boolean;
  error_count: number;
  warning_count: number;
}

export interface GeneratedPost {
  content: string;
  hook: string | null;
  validation: ValidationResult;
  post_id: string | null;
}

export interface AutoGeneratedPost extends GeneratedPost {
  pillar_name: string;
  template_name: string;
  suggested_angle: string;
  reasoning: string;
}

export interface CarouselSlide {
  slide_type: string;
  title: string;
  body: string;
  stat_number: string;
  stat_label: string;
  subtitle: string;
}

export interface Competitor {
  id: string;
  name: string;
  linkedin_url: string;
  is_active: boolean;
  created_at: string;
}

export interface CompetitorPost {
  id: string;
  competitor_name?: string;
  content: string;
  full_content?: string;
  post_type: string | null;
  likes: number;
  comments: number;
  shares: number;
  detected_topic: string | null;
  detected_template: string | null;
  relevance_score: number | null;
  analysis: Record<string, unknown> | null;
  posted_at: string | null;
  scraped_at?: string;
}

export interface Trend {
  topic: string;
  post_count: number;
  total_engagement: number;
  avg_relevance: number;
  trend_score: number;
}

export interface Recommendation {
  type: string;
  title: string;
  detail: string;
}

export interface Comment {
  id: string;
  post_id: string;
  author_name: string;
  author_headline: string | null;
  content: string;
  suggested_reply: string | null;
  approved_reply: string | null;
  reply_status: string;
  is_prospect: boolean;
  priority: string;
  commented_at: string | null;
  replied_at: string | null;
}

export interface Product {
  id: string;
  name: string;
  slug: string;
  tagline: string;
  description: string;
  target_audience: string;
  key_benefits: string[];
  pain_points: string[];
  proof_points: string[] | null;
  cta_text: string | null;
  price_info: string | null;
  url: string | null;
  display_order: number;
  is_active: boolean;
}

export interface VisualSuggestion {
  visual_type: string;
  reasoning: string;
  visual_description: string;
  carousel_slides: { slide_number: number; title: string; content: string; visual_note: string }[] | null;
}

export interface BrandConfig {
  primary_color: string;
  secondary_color: string;
  bg_color: string;
  text_color: string;
  light_text_color: string;
  accent_bg_color: string;
  highlight_color: string;
  author_name: string;
  author_title: string;
  logo_text: string;
  font_titles: string;
  font_body: string;
}

export interface ContentPlanDay {
  date: string;
  day_name: string;
  pillar_name: string;
  template_slug: string;
  format: string;
  topic: string;
  hook_idea: string;
  idea_id: string | null;
}

class ApiClient {
  // Single-user mode — no auth token needed
  setToken(_token: string) {}
  getToken(): string | null { return null; }

  private async request<T>(path: string, options: RequestInit = {}): Promise<T> {
    const headers: HeadersInit = {
      "Content-Type": "application/json",
      ...options.headers,
    };

    const response = await fetch(`${API_BASE}${path}`, { ...options, headers });

    if (!response.ok) {
      const error = await response.json().catch(() => ({}));
      throw new Error(error.detail || `API error: ${response.status}`);
    }

    if (response.status === 204) return undefined as T;
    return response.json();
  }

  // Auth
  async login(email: string, password: string) {
    const formData = new URLSearchParams();
    formData.append("username", email);
    formData.append("password", password);
    const response = await fetch(`${API_BASE}/auth/login`, {
      method: "POST",
      headers: { "Content-Type": "application/x-www-form-urlencoded" },
      body: formData,
    });
    if (!response.ok) throw new Error("Invalid credentials");
    const data = await response.json();
    this.setToken(data.access_token);
    return data;
  }

  async register(email: string, password: string, fullName: string) {
    return this.request("/auth/register", {
      method: "POST",
      body: JSON.stringify({ email, password, full_name: fullName }),
    });
  }

  async me() {
    return this.request("/auth/me");
  }

  // Posts
  async listPosts(params?: { status?: string; pillar_id?: string }): Promise<Post[]> {
    const query = params ? "?" + new URLSearchParams(params as Record<string, string>) : "";
    return this.request(`/posts/${query}`);
  }

  async createPost(data: Partial<Post>): Promise<Post> {
    return this.request("/posts/", { method: "POST", body: JSON.stringify(data) });
  }

  async updatePost(id: string, data: Partial<Post>): Promise<Post> {
    return this.request(`/posts/${id}`, { method: "PATCH", body: JSON.stringify(data) });
  }

  async deletePost(id: string): Promise<void> {
    return this.request(`/posts/${id}`, { method: "DELETE" });
  }

  // Ideas
  async listIdeas(params?: { status?: string }): Promise<Idea[]> {
    const query = params ? "?" + new URLSearchParams(params as Record<string, string>) : "";
    return this.request(`/ideas/${query}`);
  }

  async createIdea(data: { input_type: string; raw_input: string; source_url?: string }): Promise<Idea> {
    return this.request("/ideas/", { method: "POST", body: JSON.stringify(data) });
  }

  async updateIdea(id: string, data: Partial<Idea>): Promise<Idea> {
    return this.request(`/ideas/${id}`, { method: "PATCH", body: JSON.stringify(data) });
  }

  async generateIdeaBank(data: {
    count?: number;
    pillar_id?: string;
    save?: boolean;
  }): Promise<{
    ideas: {
      title: string;
      description: string;
      pillar_id: string;
      pillar_name: string;
      template_id: string;
      template_name: string;
      priority: string;
      tags: string[];
    }[];
    generated: number;
    saved: number;
  }> {
    return this.request("/ideas/generate-bank", { method: "POST", body: JSON.stringify(data) });
  }

  async deleteIdea(id: string): Promise<void> {
    return this.request(`/ideas/${id}`, { method: "DELETE" });
  }

  async generateFromBrief(data: {
    brief: string;
    count?: number;
    channel?: string;
    save_selected?: number[];
  }): Promise<{
    ideas: {
      title: string;
      description: string;
      pillar_id: string;
      pillar_name: string;
      template_id: string;
      template_name: string;
      hook_preview: string;
      priority: string;
      tags: string[];
      channel: string;
    }[];
    generated: number;
    saved: number;
  }> {
    return this.request("/ideas/generate-from-brief", { method: "POST", body: JSON.stringify(data) });
  }

  async webResearch(data?: {
    num_queries?: number;
    ideas_count?: number;
    save?: boolean;
  }): Promise<{
    ideas: {
      title: string;
      description: string;
      pillar_id: string;
      pillar_name: string;
      template_id: string;
      template_name: string;
      priority: string;
      tags: string[];
      source_urls: string[];
      research_insight: string;
    }[];
    generated: number;
    saved: number;
  }> {
    return this.request("/ideas/web-research", { method: "POST", body: JSON.stringify(data || {}) });
  }

  // Pillars
  async listPillars(): Promise<Pillar[]> {
    return this.request("/pillars/");
  }

  async createPillar(data: Partial<Pillar>): Promise<Pillar> {
    return this.request("/pillars/", { method: "POST", body: JSON.stringify(data) });
  }

  async updatePillar(id: string, data: Partial<Pillar>): Promise<Pillar> {
    return this.request(`/pillars/${id}`, { method: "PATCH", body: JSON.stringify(data) });
  }

  async deletePillar(id: string): Promise<void> {
    return this.request(`/pillars/${id}`, { method: "DELETE" });
  }

  // Templates
  async listTemplates(): Promise<PostTemplate[]> {
    return this.request("/templates/");
  }

  async updateTemplate(id: string, data: Partial<PostTemplate>): Promise<PostTemplate> {
    return this.request(`/templates/${id}`, { method: "PATCH", body: JSON.stringify(data) });
  }

  // Writing Rules
  async listRules(category?: string): Promise<WritingRule[]> {
    const query = category ? `?category=${category}` : "";
    return this.request(`/writing-rules/${query}`);
  }

  async createRule(data: Partial<WritingRule>): Promise<WritingRule> {
    return this.request("/writing-rules/", { method: "POST", body: JSON.stringify(data) });
  }

  async updateRule(id: string, data: Partial<WritingRule>): Promise<WritingRule> {
    return this.request(`/writing-rules/${id}`, { method: "PATCH", body: JSON.stringify(data) });
  }

  async deleteRule(id: string): Promise<void> {
    return this.request(`/writing-rules/${id}`, { method: "DELETE" });
  }

  // AI Generation
  async generatePost(data: {
    pillar_id: string;
    template_id: string;
    topic?: string;
    additional_context?: string;
    save_as_draft?: boolean;
  }): Promise<GeneratedPost> {
    return this.request("/ai/generate", { method: "POST", body: JSON.stringify(data) });
  }

  async generateVariants(data: {
    pillar_id: string;
    template_id: string;
    topic?: string;
    count?: number;
  }): Promise<GeneratedPost[]> {
    return this.request("/ai/generate/variants", { method: "POST", body: JSON.stringify(data) });
  }

  async validatePost(content: string): Promise<ValidationResult> {
    return this.request("/ai/validate", { method: "POST", body: JSON.stringify({ content }) });
  }

  async generateAutoPost(data: {
    topic: string;
    source_url?: string;
    idea_id?: string;
    save_as_draft?: boolean;
  }): Promise<AutoGeneratedPost> {
    return this.request("/ai/generate/auto", { method: "POST", body: JSON.stringify(data) });
  }

  // Analytics
  async getAnalyticsSummary(days = 30) {
    return this.request(`/analytics/summary?days=${days}`);
  }

  // Calendar
  async getCalendar(start: string, end: string) {
    return this.request(`/calendar/?start=${start}&end=${end}`);
  }

  // Carousel
  async generateCarouselSlides(data: {
    topic: string;
    pillar_name: string;
    num_slides?: number;
  }): Promise<{ slides: CarouselSlide[] }> {
    return this.request("/carousel/generate-slides", { method: "POST", body: JSON.stringify(data) });
  }

  async generateCarouselPDF(data: {
    slides: CarouselSlide[];
    save_as_draft?: boolean;
    pillar_id?: string;
    template_id?: string;
  }): Promise<{ pdf_base64: string; post_id: string | null }> {
    return this.request("/carousel/generate-pdf", { method: "POST", body: JSON.stringify(data) });
  }

  // Competitors
  async listCompetitors(): Promise<Competitor[]> {
    return this.request("/competitors/");
  }

  async createCompetitor(data: { name: string; linkedin_url: string }): Promise<Competitor> {
    return this.request("/competitors/", { method: "POST", body: JSON.stringify(data) });
  }

  async deleteCompetitor(id: string): Promise<void> {
    return this.request(`/competitors/${id}`, { method: "DELETE" });
  }

  async getCompetitorPosts(id: string, limit = 20): Promise<CompetitorPost[]> {
    return this.request(`/competitors/${id}/posts?limit=${limit}`);
  }

  async getCompetitorTrends(days = 14): Promise<Trend[]> {
    return this.request(`/competitors/trends?days=${days}`);
  }

  async getTopCompetitorPosts(days = 14, limit = 10): Promise<CompetitorPost[]> {
    return this.request(`/competitors/top-posts?days=${days}&limit=${limit}`);
  }

  // ML
  async getRecommendations(): Promise<Recommendation[]> {
    return this.request("/ml/recommendations");
  }

  async getModelInfo(): Promise<Record<string, unknown>> {
    return this.request("/ml/model-info");
  }

  // Comments
  async listComments(params?: { status?: string; post_id?: string }): Promise<Comment[]> {
    const query = params ? "?" + new URLSearchParams(params as Record<string, string>) : "";
    return this.request(`/comments/${query}`);
  }

  async fetchPostComments(postId: string): Promise<{ new_comments: number }> {
    return this.request(`/comments/fetch/${postId}`, { method: "POST" });
  }

  async suggestReply(commentId: string): Promise<{ suggested_reply: string }> {
    return this.request(`/comments/suggest/${commentId}`, { method: "POST" });
  }

  async suggestBatchReplies(postId: string): Promise<{ suggested: number }> {
    return this.request(`/comments/suggest-batch/${postId}`, { method: "POST" });
  }

  async approveReply(commentId: string, approvedReply: string): Promise<void> {
    return this.request(`/comments/approve/${commentId}`, {
      method: "POST",
      body: JSON.stringify({ approved_reply: approvedReply }),
    });
  }

  async sendReply(commentId: string): Promise<{ status: string }> {
    return this.request(`/comments/send/${commentId}`, { method: "POST" });
  }

  async skipComment(commentId: string): Promise<void> {
    return this.request(`/comments/skip/${commentId}`, { method: "POST" });
  }

  // Smart Calendar
  async generateContentPlan(days = 7): Promise<ContentPlanDay[]> {
    return this.request("/calendar/generate-plan", {
      method: "POST",
      body: JSON.stringify({ days }),
    });
  }

  async regenerateDay(date: string, constraints?: string): Promise<ContentPlanDay> {
    return this.request("/calendar/regenerate-day", {
      method: "POST",
      body: JSON.stringify({ date, constraints }),
    });
  }

  // Case Study
  async generateCaseStudy(data: {
    client_name: string;
    industry: string;
    problem: string;
    actions: string;
    results: string;
    anonymize?: boolean;
    additional_context?: string;
    save_as_draft?: boolean;
  }): Promise<Record<string, unknown>> {
    return this.request("/ai/generate/case-study", { method: "POST", body: JSON.stringify(data) });
  }

  // Email Inbox
  async getEmailConfig(): Promise<{ configured: boolean; email_address: string | null; imap_host: string | null }> {
    return this.request("/email-inbox/config");
  }

  async updateEmailConfig(data: {
    imap_host: string;
    imap_port: number;
    email_address: string;
    email_password: string;
  }): Promise<{ status: string; message: string }> {
    return this.request("/email-inbox/config", { method: "POST", body: JSON.stringify(data) });
  }

  async pollEmails(): Promise<{ processed: number; errors: number; details: string[] }> {
    return this.request("/email-inbox/poll", { method: "POST" });
  }

  // Products
  async listProducts(): Promise<Product[]> {
    return this.request("/products/");
  }

  async createProduct(data: Partial<Product>): Promise<Product> {
    return this.request("/products/", { method: "POST", body: JSON.stringify(data) });
  }

  async updateProduct(id: string, data: Partial<Product>): Promise<Product> {
    return this.request(`/products/${id}`, { method: "PATCH", body: JSON.stringify(data) });
  }

  async deleteProduct(id: string): Promise<void> {
    return this.request(`/products/${id}`, { method: "DELETE" });
  }

  // Visual Suggestions
  async suggestVisual(content: string, pillarName?: string): Promise<VisualSuggestion> {
    return this.request("/ai/suggest-visual", {
      method: "POST",
      body: JSON.stringify({ content, pillar_name: pillarName || "" }),
    });
  }

  // Branding
  async getBrandConfig(): Promise<BrandConfig> {
    return this.request("/branding/");
  }

  async updateBrandConfig(data: Partial<BrandConfig>): Promise<BrandConfig> {
    return this.request("/branding/", { method: "PATCH", body: JSON.stringify(data) });
  }

  async resetBrandConfig(): Promise<BrandConfig> {
    return this.request("/branding/reset", { method: "POST" });
  }
}

export const api = new ApiClient();
